In [2]:
import pandas as pd

# SAIL2025_LVMA

In [3]:
SAIL2025_LVMA = pd.read_csv("Data/SAIL2025_LVMA.csv")

SAIL2025_LVMA.head(5)

,timestamp,CMSA-GAKH-01_0,CMSA-GAKH-01_180,CMSA-GAWW-11_120,CMSA-GAWW-11_300,CMSA-GAWW-12_115,CMSA-GAWW-12_295,CMSA-GAWW-13_120,CMSA-GAWW-13_300,CMSA-GAWW-14_40,...,GVCV-13_10,GVCV-13_190,GVCV-14_90,GVCV-14_270,hour,minute,day,month,weekday,is_weekend
0,2025-08-20 00:00:00+02:00,15,4,29,33,44,28,42,37,11,...,41,40,0,0,0,0,20,8,2,0
1,2025-08-20 00:03:00+02:00,1,3,21,29,34,39,9,14,6,...,0,0,0,0,0,3,20,8,2,0
2,2025-08-20 00:06:00+02:00,5,4,35,22,29,34,33,42,14,...,0,0,0,0,0,6,20,8,2,0
3,2025-08-20 00:09:00+02:00,4,4,40,47,42,40,19,34,15,...,0,0,0,0,0,9,20,8,2,0
4,2025-08-20 00:12:00+02:00,4,11,54,59,58,33,17,33,26,...,127,57,0,0,0,12,20,8,2,0

Based on README file, this DataFrame contains pedestrian crowd flow counts. Most columns are sensors.

In [4]:
SAIL2025_LVMA["timestamp"].size

2400

In [14]:
pd.set_option('display.max_columns', None)

In [17]:
SAIL2025_LVMA.describe()

,CMSA-GAKH-01_0,CMSA-GAKH-01_180,CMSA-GAWW-11_120,CMSA-GAWW-11_300,CMSA-GAWW-12_115,CMSA-GAWW-12_295,CMSA-GAWW-13_120,CMSA-GAWW-13_300,CMSA-GAWW-14_40,CMSA-GAWW-14_220,CMSA-GAWW-15_30,CMSA-GAWW-15_210,CMSA-GAWW-16_30,CMSA-GAWW-16_210,CMSA-GAWW-17_40,CMSA-GAWW-17_220,CMSA-GAWW-19_115,CMSA-GAWW-19_295,CMSA-GAWW-20_120,CMSA-GAWW-20_300,CMSA-GAWW-21_120,CMSA-GAWW-21_300,CMSA-GAWW-23_109,CMSA-GAWW-23_289,GACM-04_50,GACM-04_230,GASA-01-A1_135,GASA-01-A1_315,GASA-01-A2_135,GASA-01-A2_315,GASA-01-B_135,GASA-01-B_315,GASA-01-C_135,GASA-01-C_315,GASA-02-01_135,GASA-02-01_315,GASA-02-02_135,GASA-02-02_315,GASA-03_105,GASA-03_285,GASA-04_135,GASA-04_315,GASA-05-O_135,GASA-05-O_315,GASA-05-W_135,GASA-05-W_315,GASA-06_95,GASA-06_275,GASA-06-B_95,GASA-06-B_275,GVCV-01_40,GVCV-01_220,GVCV-03_42,GVCV-03_222,GVCV-04_45,GVCV-04_225,GVCV-05-A_155,GVCV-05-A_335,GVCV-05-B_30,GVCV-05-B_210,GVCV-06_95,GVCV-06_275,GVCV-07_50,GVCV-07_230,GVCV-08_45,GVCV-08_225,GVCV-09_80,GVCV-09_260,GVCV-11_50,GVCV-11_230,GVCV-13_10,GVCV-13_190,GVCV-14_90,GVCV-14_270,hour,minute,day,month,weekday,is_weekend
count,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.00000,2400.00000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.0,2400.000000,2400.00
mean,57.513750,49.180000,37.840417,37.500417,39.021250,43.677500,20.566250,24.223333,17.682917,10.912083,25.784167,27.667083,31.23875,25.06875,23.668750,23.293333,34.465417,17.748333,24.972917,23.927083,58.222917,59.276667,8.055833,10.520000,53.148333,81.325833,10.286667,9.795417,28.301667,36.690833,12.271667,35.267083,27.609583,8.835833,15.065833,95.525000,126.797083,16.235417,110.038333,103.021667,64.394167,50.521667,17.455833,15.695417,15.971667,14.558750,0.001250,0.004167,4.695833,3.246667,12.857500,7.854583,24.338750,23.085000,21.938750,19.191250,17.906667,16.173750,17.583750,19.356250,7.391250,8.072500,6.209583,8.433750,4.374583,2.887083,0.023750,0.023333,30.751250,26.324167,32.629583,28.449583,24.782083,16.878750,11.500000,28.500000,22.000000,8.0,4.000000,0.40
std,69.204386,58.768898,36.631952,33.478431,34.266092,40.235263,24.612406,24.260349,16.685324,13.344451,28.954019,32.774489,33.65118,24.16050,22.823604,20.753536,32.638988,17.208042,28.269863,26.047094,50.850408,49.511462,8.574236,11.152343,47.832673,75.470229,13.687648,11.568787,29.047787,41.094299,15.272335,39.664484,34.049551,10.697152,26.771738,121.908521,146.770072,24.399362,124.482593,120.220245,64.901725,56.389991,22.848919,18.713615,23.324648,21.168016,0.035341,0.111749,13.794175,9.120790,26.865087,16.931245,42.988747,46.547813,42.007929,41.697651,52.999898,33.729056,36.558057,53.550708,25.732355,27.696032,20.133647,27.738698,13.043076,11.734175,0.232469,0.226149,78.573926,58.907717,67.133867,53.724243,57.345319,35.979428,6.923629,17.302449,1.414508,0.0,1.414508,0.49
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000,8.0,2.000000,0.00
25%,3.000000,2.000000,6.000000,6.000000,7.000000,7.000000,3.000000,4.000000,3.000000,2.000000,3.000000,3.000000,5.00000,4.00000,3.000000,4.000000,4.000000,3.000000,0.000000,1.000000,8.000000,9.000000,2.000000,2.000000,10.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2.000000,1.000000,7.000000,4.000000,4.000000,3.000000,1.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.750000,14.250000,21.000000,8.0,3.000000,0.00
50%,17.000000,15.000000,30.000000,32.000000,32.000000,36.000000,12.000000,17.000000,13.000000,7.000000,15.000000,16.000000,21.00000,19.00000,17.000000,20.000000,27.000000,14.000000,11.000000,13.000000,49.000000,55.000000,5.000000,7.000000,40.000000,65.000000,5.000000,5.000000,21.000000,25.000000,7.000000,24.000000,14.000000,6.000000,6.000000,19.500000,57.500000,6.000000,49.500000,35.500000,48.500000,31.000000,12.000000,13.000000,11.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,11.500000,28.500000,22.000000,8.0,4.000000,0.00
75%,110.250000,95.000000,59.000000,61.000000,62.000000,68.000000,28.000000,37.000000,28.000000,15.000000,40.000000,39.000000,44.00000,39.00000,40.000000,37.000000,56.000000,28.000000,47.000000,44.000000,103.000000,99.000000,12.000000,16.000000,89.000000,144.000000,17.000000,17.000000,51.000000,62.000000,19.000000,56.250000,43.000000,13.000000,17.250000,184.250000,226.000000,20.000000,204.000000,194.000000,110.000000,83.000000,25.000000,22.000000,20.000000,19.000000,0.000000,0.000000,2.000000,2.000000,9.000000,6.000000,31.000000,19.000000,25.000000,8.000000,3.000000,15.000000,16.000000,3.000000,0.250000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,15.250000,26.000000,35.000000,7.000000,17.000000,17.250000,42.750000,23.000000,8.0,5.000000,1.00
max,266.000000,257.000000,246.000000,156.000000,168.000000,230.000000,166.000000,124.000000,123.000000,141.000000,188.000000,212.000000,218.00000,148.00000,123.000000,114.000000,167.000000,93.000000,140.000000,137.000000,225.000000,387.000000,61.000000,120.000000,212.000000,318.000000,129.000000,83.000000,134.000000,263.000000,115.000000,291.000000,211.000000,114.000000,253.000000,588.000000,599.000000,200.000000,542.000000,718.000000,291.000000,362.000000,205.000000,160.000000,249.000000,192.000000,1.000000,4.000000,164.000000,83.000000,173.000000,133.000000,249.000000,284.000000,261.000000,280.000000,424.000000,245.000000,303.000000,362.000000,262.000000,287.000000,168.000000,268.000000,117.000000,326.000000,4.000000,4.000000,528.000000,396.000000,396.000000,339.000000,381.000000,280.000000,23.000000,57.000000,24.000000,8.0,6.000000,1.00

Depending on the day, the hours of the SAIL event vary. We create masks to keep rows that only measure during these hours. When joining the columns we realized that some rows had hours or minutes without 2 digits. For example, 04:05 was 4 in column hour and 5 in column minute. We had to change this for the masks.

In [31]:
SAIL2025_LVMA["hourminute"] = (SAIL2025_LVMA["hour"].astype(str).str.zfill(2) + SAIL2025_LVMA["minute"].astype(str).str.zfill(2))
SAIL2025_LVMA["hourminute"] = SAIL2025_LVMA["hourminute"].astype(int)

In [33]:
wen = (SAIL2025_LVMA["day"] == 20) & (SAIL2025_LVMA["hourminute"] >= 1000) & (SAIL2025_LVMA["hourminute"] <= 2245)
thu = (SAIL2025_LVMA["day"] == 21) & (SAIL2025_LVMA["hourminute"] >= 800) & (SAIL2025_LVMA["hourminute"] <= 2245)
fri = (SAIL2025_LVMA["day"] == 22) & (SAIL2025_LVMA["hourminute"] >= 900) & (SAIL2025_LVMA["hourminute"] <= 2245)
sat = (SAIL2025_LVMA["day"] == 23) & (SAIL2025_LVMA["hourminute"] >= 900) & (SAIL2025_LVMA["hourminute"] <= 2245)
sun = (SAIL2025_LVMA["day"] == 24) & (SAIL2025_LVMA["hourminute"] >= 900) & (SAIL2025_LVMA["hourminute"] <= 2100)

In [38]:
filtered = SAIL2025_LVMA[wen | thu | fri | sat | sun]
len(filtered.index)

1345

Making this filters we get roughly 1000 rows less compared to the original dataframe.

In [45]:
filtered.isna().sum().sum() # No missing values

np.int64(0)

Now check if there are zero value readings in any sensors during this period to detect malfunctions.

In [46]:
for column in filtered.columns:

    temp = filtered[filtered[column] == 0]
    print(f"{column} - {len(temp.index)}")

timestamp - 0
CMSA-GAKH-01_0 - 6
CMSA-GAKH-01_180 - 6
CMSA-GAWW-11_120 - 4
CMSA-GAWW-11_300 - 4
CMSA-GAWW-12_115 - 8
CMSA-GAWW-12_295 - 4
CMSA-GAWW-13_120 - 37
CMSA-GAWW-13_300 - 23
CMSA-GAWW-14_40 - 12
CMSA-GAWW-14_220 - 27
CMSA-GAWW-15_30 - 32
CMSA-GAWW-15_210 - 19
CMSA-GAWW-16_30 - 9
CMSA-GAWW-16_210 - 17
CMSA-GAWW-17_40 - 12
CMSA-GAWW-17_220 - 5
CMSA-GAWW-19_115 - 11
CMSA-GAWW-19_295 - 26
CMSA-GAWW-20_120 - 294
CMSA-GAWW-20_300 - 292
CMSA-GAWW-21_120 - 24
CMSA-GAWW-21_300 - 29
CMSA-GAWW-23_109 - 35
CMSA-GAWW-23_289 - 34
GACM-04_50 - 0
GACM-04_230 - 0
GASA-01-A1_135 - 56
GASA-01-A1_315 - 63
GASA-01-A2_135 - 33
GASA-01-A2_315 - 31
GASA-01-B_135 - 22
GASA-01-B_315 - 8
GASA-01-C_135 - 17
GASA-01-C_315 - 29
GASA-02-01_135 - 75
GASA-02-01_315 - 91
GASA-02-02_135 - 62
GASA-02-02_315 - 103
GASA-03_105 - 0
GASA-03_285 - 1
GASA-04_135 - 0
GASA-04_315 - 0
GASA-05-O_135 - 5
GASA-05-O_315 - 1
GASA-05-W_135 - 1
GASA-05-W_315 - 5
GASA-06_95 - 1345
GASA-06_275 - 1345
GASA-06-B_95 - 663
GASA-06-B_275 - 647
GVCV-01_40 - 535
GVCV-01_220 - 552
GVCV-03_42 - 411
GVCV-03_222 - 409
GVCV-04_45 - 541
GVCV-04_225 - 558
GVCV-05-A_155 - 551
GVCV-05-A_335 - 480
GVCV-05-B_30 - 491
GVCV-05-B_210 - 536
GVCV-06_95 - 894
GVCV-06_275 - 854
GVCV-07_50 - 944
GVCV-07_230 - 959
GVCV-08_45 - 903
GVCV-08_225 - 955
GVCV-09_80 - 1321
GVCV-09_260 - 1321
GVCV-11_50 - 549
GVCV-11_230 - 478
GVCV-13_10 - 564
GVCV-13_190 - 530
GVCV-14_90 - 544
GVCV-14_270 - 509
hour - 0
minute - 69
day - 0
month - 0
weekday - 0
is_weekend - 828
hourminute - 0

In [47]:
filtered[filtered["GVCV-09_80"] != 0]

,timestamp,CMSA-GAKH-01_0,CMSA-GAKH-01_180,CMSA-GAWW-11_120,CMSA-GAWW-11_300,CMSA-GAWW-12_115,CMSA-GAWW-12_295,CMSA-GAWW-13_120,CMSA-GAWW-13_300,CMSA-GAWW-14_40,CMSA-GAWW-14_220,CMSA-GAWW-15_30,CMSA-GAWW-15_210,CMSA-GAWW-16_30,CMSA-GAWW-16_210,CMSA-GAWW-17_40,CMSA-GAWW-17_220,CMSA-GAWW-19_115,CMSA-GAWW-19_295,CMSA-GAWW-20_120,CMSA-GAWW-20_300,CMSA-GAWW-21_120,CMSA-GAWW-21_300,CMSA-GAWW-23_109,CMSA-GAWW-23_289,GACM-04_50,GACM-04_230,GASA-01-A1_135,GASA-01-A1_315,GASA-01-A2_135,GASA-01-A2_315,GASA-01-B_135,GASA-01-B_315,GASA-01-C_135,GASA-01-C_315,GASA-02-01_135,GASA-02-01_315,GASA-02-02_135,GASA-02-02_315,GASA-03_105,GASA-03_285,GASA-04_135,GASA-04_315,GASA-05-O_135,GASA-05-O_315,GASA-05-W_135,GASA-05-W_315,GASA-06_95,GASA-06_275,GASA-06-B_95,GASA-06-B_275,GVCV-01_40,GVCV-01_220,GVCV-03_42,GVCV-03_222,GVCV-04_45,GVCV-04_225,GVCV-05-A_155,GVCV-05-A_335,GVCV-05-B_30,GVCV-05-B_210,GVCV-06_95,GVCV-06_275,GVCV-07_50,GVCV-07_230,GVCV-08_45,GVCV-08_225,GVCV-09_80,GVCV-09_260,GVCV-11_50,GVCV-11_230,GVCV-13_10,GVCV-13_190,GVCV-14_90,GVCV-14_270,hour,minute,day,month,weekday,is_weekend,hourminute
350,2025-08-20 17:30:00+02:00,159,135,61,67,53,45,10,29,21,10,31,27,16,16,56,57,28,28,62,44,133,88,1,19,92,176,16,31,29,78,60,96,29,12,44,214,318,43,242,114,122,149,154,115,191,123,0,0,1,4,0,0,0,0,0,0,3,114,7,5,0,110,0,0,51,1,2,0,183,17,52,2,88,4,17,30,20,8,2,0,1730
362,2025-08-20 18:06:00+02:00,165,121,90,45,99,47,37,34,34,8,27,27,45,32,46,65,18,16,65,80,109,96,4,13,57,99,14,11,26,30,11,41,47,5,38,127,165,56,118,138,94,64,23,40,54,37,0,0,50,8,0,0,4,133,0,0,205,78,2,1,1,108,2,1,0,0,1,0,88,243,58,7,0,0,18,6,20,8,2,0,1806
377,2025-08-20 18:51:00+02:00,91,69,62,51,52,74,12,26,26,7,17,10,47,32,44,26,36,27,71,68,121,88,6,15,72,82,23,1,25,57,6,18,11,24,29,173,189,36,120,78,92,50,46,21,52,52,0,0,0,0,50,21,5,0,20,0,218,117,0,202,0,0,0,5,76,46,2,1,1,1,0,0,0,0,18,51,20,8,2,0,1851
391,2025-08-20 19:33:00+02:00,62,35,64,57,71,34,22,39,13,12,27,47,37,27,45,41,53,24,87,59,162,62,9,6,101,88,22,37,30,32,23,69,127,8,25,159,272,49,131,222,89,87,27,36,54,81,0,0,3,3,1,11,0,0,47,4,0,0,0,0,0,0,0,0,2,2,1,2,2,0,0,0,1,48,19,33,20,8,2,0,1933
408,2025-08-20 20:24:00+02:00,60,36,65,106,81,51,32,51,24,11,16,42,42,26,57,33,74,17,39,50,97,74,30,18,82,111,24,20,46,51,4,27,46,22,12,169,167,41,92,196,66,81,3,16,8,10,0,0,38,4,48,33,28,3,0,0,0,0,41,12,3,0,0,0,43,36,3,0,0,0,0,0,152,35,20,24,20,8,2,0,2024
415,2025-08-20 20:45:00+02:00,44,28,91,77,76,72,50,60,41,23,66,49,54,40,50,32,71,34,72,40,102,104,24,26,93,119,28,27,72,67,11,36,18,24,10,149,146,61,125,219,72,56,21,15,13,34,0,0,3,29,0,0,82,0,0,0,22,33,0,0,0,63,0,0,0,0,4,4,1,3,0,0,1,33,20,45,20,8,2,0,2045
420,2025-08-20 21:00:00+02:00,23,23,61,80,81,125,27,74,27,12,69,64,100,65,55,33,97,35,47,30,117,99,16,23,91,70,14,19,53,66,20,16,22,12,15,184,142,29,89,203,46,74,7,11,8,12,0,0,1,3,51,33,0,0,0,0,1,23,0,1,2,0,3,0,8,0,1,1,0,0,105,1,4,13,21,0,20,8,2,0,2100
689,2025-08-21 10:27:00+02:00,19,34,5,6,13,27,2,0,10,2,0,6,12,6,10,13,12,23,18,15,44,36,5,5,23,74,6,13,36,32,11,25,15,12,12,14,333,3,248,24,141,7,19,17,14,6,0,0,0,0,0,0,0,101,35,1,94,10,11,0,0,0,0,3,3,0,1,1,0,0,0,0,74,45,10,27,21,8,3,0,1027
892,2025-08-21 20:36:00+02:00,99,32,98,50,89,108,46,72,40,13,48,46,95,51,40,66,95,40,77,44,85,105,23,25,69,61,23,13,12,57,1,15,3,10,17,170,114,9,144,85,27,45,21,9,11,11,0,0,0,1,0,0,0,2,2,3,0,1,77,1,0,0,0,0,0,0,3,0,30,2,0,0,116,30,20,36,21,8,3,0,2036
893,2025-08-21 20:39:00+02:00,82,50,84,76,87,84,37,47,67,8,50,78,56,39,47,56,80,60,64,55,104,117,10,20,94,61,19,17,35,34,28,45,39,11,14,183,129,31,157,154,68,68,7,14,10,2,0,0,0,0,0,0,104,209,0,0,0,0,44,1,0,0,0,0,0,0,3,3,213,163,0,0,4,106,20,39,21,8,3,0,2039
1281,2025-08-22 16:03:00+02:00,158,173,57,57,60,29,19,13,25,22,28,12,32,27,44,17,46,24,59,69,104,105,11,10,86,135,12,46,59,63,18,52,4,10,29,224,381,4,350,331,157,84,36,37,33,31,0,0,21,1,0,0,1,0,49,4,170,1,21,0,101,0,111,34,58,20,1,2,0,3,208,76,1,22,16,3,22,8,4,0,1603
1282,2025-08-22 16:06:00+02:00,164,184,43,140,58,76,13,21,16,26,38,27,17,25,30,32,46,65,52,66,99,82,15,17,110,240,22,29,28,72,15,93,6,11,17,391,319,8,363,291,150,77,39,29,19,26,0,0,16,1,7,1,1,1,0,0,105,103,0,0,68,1,1,0,0,0,1,0,202,0,3,127,0,0,16,6,22,8,4,0,1606
1283,2025-08-22 16:09:00+02:00,200,109,45,75,57,108,8,55,9,21,2,23,21,148,18,75,57,46,64,137,54,259,7,120,162,172,24,19,40,54,22,28,24,16,4,326,306,6,295,291,122,147,6,26,3,12,0,0,46,3,6,0,0,221,0,0,7,49,1,170,0,3,0,0,0,0,3,2,172,171,0,0,205,7,16,9,22,8,4,0,1609
1387,2025-08-22 21:21:00+02:00,31,10,108,82,113,90,93,36,35,10,95,123,99,120,44,21,98,50,85,58,130,69,14,21,117,84,28,19,62,54,17,23,38,9,4,186,259,4,145,159,89,60,5,9,16,9,0,0,33,3,0,0,63,44,23,0,16,31,1,224,0,0,13,32,14,3,2,3,0,10,0,45,0,0,21,21,22,8,4,0,2121
1716,2025-08-23 13:48:00+02:00,94,81,39,48,29,44,12,15,9,2,16,11,20,10,24,34,18,22,37,43,127,82,3,11,95,208,23,21,82,111,49,86,93,18,103,215,538,7,361,252,203,102,25,13,26,23,0,0,7,2,50,2,6,5,72,9,5,95,0,0,0,4,0,0,79,11,2,2,367,69,0,0,269,55,13,48,23,8,5,1,1348
1782,2025-08-23 17:06:00+02:00,206,188,81,102,110,93,27,48,70,29,47,34,42,46,63,70,94,26,75,93,140,192,17,20,169,258,23,42,67,108,25,154,45,41,33,388,526,1,310,426,224,310,24,33,17,27,0,0,0,41,6,30,85,152,0,0,0,2,3,138,54,1,90,119,0,0,1,1,183,197,112,110,246,54,17,6,23,8,5,1,1706
1783,2025-08-23 17:09:00+02:00,138,112,75,59,63,55,18,22,25,13,38,42,35,30,49,36,43,26,72,55,98,125,3,3,172,255,38,34,56,81,38,82,77,34,32,453,454,8,297,403,150,159,35,40,24,25,0,0,3,28,76,18,129,18,0,0,119,3,183,303,228,2,46,3,42,39,1,1,3,175,3,178,1,197,17,9,23,8,5,1,1709
1784,2025-08-23 17:12:00+02:00,233,186,66,53,80,94,36,39,39,15,62,49,50,36,56,89,109,30,78,58,177,131,13,16,188,202,31,39,48,99,22,111,96,22,11,508,486,20,235,394,223,156,11,32,17,30,0,0,0,8,7,8,1,6,0,0,169,117,133,2,114,6,2,2,3,0,1,0,0,0,0,2,0,8,17,12,23,8,5,1,1712
1803,2025-08-23 18:09:00+02:00,223,144,97,72,131,98,30,48,53,28,62,51,49,70,74,68,96,24,78,88,169,132,16,22,72,176,56,18,74,103,83,100,114,7,30,397,514,7,182,348,150,213,31,15,13,41,0,0,103,3,41,7,1,0,5,194,92,0,12,0,0,0,0,0,19,1,2,0,0,0,0,0,284,3,18,9,23,8,5,1,1809
1813,2025-08-23 18:39:00+02:00,129,72,69,59,53,57,13,45,32,17,47,40,68,25,42,19,57,26,50,44,99,87,11,11,144,128,60,25,78,60,34,57,132,5,19,331,327,4,247,343,127,228,25,10,17,23,0,0,0,0,13,9,0,0,140,74,212,0,0,0,75,3,43,163,6,30,3,3,4,271,0,0,272,9,18,39,23,8,5,1,1839
2143,2025-08-24 11:09:00+02:00,23,39,26,5,8,11,8,5,21,0,15,2,7,13,11,22,10,7,0,0,28,26,11,14,29,122,17,9,38,86,13,21,11,6,54,41,428,4,440,51,142,50,17,19,15,18,0,0,0,0,0,0,4,79,7,2,3,22,3,116,0,0,0,0,0,4,2,0,97,3,0,0,0,54,11,9,24,8,6,1,1109
2144,2025-08-24 11:12:00+02:00,27,61,13,17,17,36,1,5,3,21,14,10,7,20,11,13,7,8,0,0,55,68,8,4,43,127,10,17,47,37,16,15,15,9,17,52,230,1,248,28,77,19,8,8,8,5,0,0,29,2,36,10,33,14,0,0,2,0,56,1,96,33,0,0,0,2,1,2,119,99,51,0,2,41,11,12,24,8,6,1,1112
2146,2025-08-24 11:18:00+02:00,44,55,22,14,12,14,2,13,9,4,11,9,8,15,11,15,14,3,0,0,52,59,4,9,39,122,32,19,70,59,22,50,31,4,33,61,353,1,368,86,128,27,12,17,17,11,0,0,12,4,16,1,0,0,60,75,70,1,7,2,0,1,0,46,0,0,1,2,2,2,0,48,1,0,11,18,24,8,6,1,1118
2167,2025-08-24 12:21:00+02:00,95,102,23,26,42,27,4,19,19,8,8,8,25,21,12,13,31,11,0,0,66,77,5,2,52,188,29,19,44,82,68,55,17,15,24,83,275,4,194,82,174,107,18,9,13,23,0,0,0,0,100,10,0,2,16,0,0,2,104,2,0,0,33,65,0,0,2,0,0,2,0,4,227,2,12,21,24,8,6,1,1221

# sensor-location

In [6]:
sensor_location = pd.read_excel("Data/sensor-location.xlsx")

In [7]:
sensor_location.head(5)

,Objectummer,Locatienaam,Lat/Long,Breedte,Effectieve breedte
0,CMSA-GAKH-01,Kalverstraat t.h.v. 1,"52.372634, 4.892071",8,"6,7"
1,CMSA-GAWW-11,Korte Niezel,"52.374616, 4.899830","3,8","3,4"
2,CMSA-GAWW-12,Oudekennissteeg,"52.373860, 4.898690",3,"2,6"
3,CMSA-GAWW-13,Stoofsteeg,"52.372439, 4.897689","2,6","2,2"
4,CMSA-GAWW-14,Oudezijds Voorburgwal t.h.v. 91,"52.373538, 4.898166",4,"3,6"

- Objectummer - Censor name
- Locatienaam - Location name
- Lat/Long - Coordinates of censor
- Breedte - Sensor width
- Effective breedte - Effective width of the censor.

In [8]:
sensor_location[['Latitude', 'Longitude']] = sensor_location["Lat/Long"].str.split(",", expand=True).astype(float)

sensor_location.head()

,Objectummer,Locatienaam,Lat/Long,Breedte,Effectieve breedte,Latitude,Longitude
0,CMSA-GAKH-01,Kalverstraat t.h.v. 1,"52.372634, 4.892071",8,"6,7",52.372634,4.892071
1,CMSA-GAWW-11,Korte Niezel,"52.374616, 4.899830","3,8","3,4",52.374616,4.899830
2,CMSA-GAWW-12,Oudekennissteeg,"52.373860, 4.898690",3,"2,6",52.373860,4.898690
3,CMSA-GAWW-13,Stoofsteeg,"52.372439, 4.897689","2,6","2,2",52.372439,4.897689
4,CMSA-GAWW-14,Oudezijds Voorburgwal t.h.v. 91,"52.373538, 4.898166",4,"3,6",52.373538,4.898166

In [9]:
sensor_location = sensor_location[["Objectummer", "Latitude", "Longitude"]]

sensor_location.head(5)

    Objectummer   Latitude  Longitude
0  CMSA-GAKH-01  52.372634   4.892071
1  CMSA-GAWW-11  52.374616   4.899830
2  CMSA-GAWW-12  52.373860   4.898690
3  CMSA-GAWW-13  52.372439   4.897689
4  CMSA-GAWW-14  52.373538   4.898166

# Vesselposition

In [48]:
vessels = pd.read_csv("Data/Vesselposition_data_20-24Aug2025.csv")

C:\Users\mateo\AppData\Local\Temp\ipykernel_7272\710290921.py:1: DtypeWarning: Columns (32: name) have mixed types. Specify dtype option on import or set low_memory=False.
  vessels = pd.read_csv("Data/Vesselposition_data_20-24Aug2025.csv")

In [49]:
len(vessels.columns)

33

In [50]:
len(vessels.index)

12641979

There are more than 12 million columns, so we will start working with filters to make data more managable.

In [51]:
vessels.head()

,identifier-sensor,radar-length-cm,radar-beam-cm,position-x,position-y,speed-in-centimeters-per-second,x-speed,y-speed,orientation,significant-orientation,destination,pilot-on-board,track-number,imo-number,mmsi-number,eni-number,sensor-type,ais-length-cm,ais-beam-cm,update-time,type,sub-category,length,beam,port-role,short-term-avg-speed-in-cm-per-sec,lon,lat,id,upload-timestamp,oud_bericht,stale_since,name
0,251,2500,1200,100561.0,497650.0,30,-15,-26,209.9,NaN,HARBOUR ASSISTING,False,4450,745900ce09e5bcd3ad26ca148ed421298442f6f29a29ef...,4e73147932245214a49503c66d37ccb8e04dc06299fbf5...,NaN,AIS_AND_RADAR,2500,1200,2025-08-20T06:33:43+00:00,TUG,Tug,2500.0,1100.0,TUG_VESSEL,97.0,4.586152,52.463890,14523957174087988532,2025-08-20T06:34:08.177626Z,False,NaN,NaN
1,13212,2000,600,100329.0,497504.0,160,-151,53,289.5,NaN,NaN,False,8870,cff0a521594265f8f2858910679298ebaccda2b18785dc...,dfb315a6b5cff224394af277e0053d057db332a988ccc3...,NaN,AIS,1800,800,2025-08-20T06:33:43+00:00,YACHT,Sail Training Ship,2000.0,600.0,NaN,165.0,4.582762,52.462554,8410171728078482327,2025-08-20T06:34:08.181693Z,False,NaN,NaN
2,390,3300,1200,106036.0,498034.0,0,0,0,0.1,0.1,VELSEN,False,11964,2869e3dc53f76fb9395592febec8615c89ca36c7078b97...,0d11ea82dff9438409d2a9f3416802933496c659a0fa84...,NaN,AIS,3300,1200,2025-08-20T06:33:43+00:00,TUG,Tug,3300.0,1200.0,NaN,0.0,4.666652,52.467857,15111480980279746939,2025-08-20T06:34:08.196046Z,False,NaN,NaN
3,392,3600,800,105998.0,497971.0,0,0,0,0.1,0.1,AMSTERDAM,False,3644,NaN,e324f61d2312f715bfa3a70729570922528bcb0172e58c...,65d3845c259199b415346456c03b004d55c9bb2b6db69d...,AIS,3400,800,2025-08-20T06:33:43+00:00,8490,NaN,3400.0,700.0,NaN,0.0,4.666102,52.467288,8852227552724661228,2025-08-20T06:34:08.200039Z,False,NaN,NaN
4,10247,2000,300,106238.0,497017.0,240,-196,138,305.2,NaN,AMSTERDAM,False,11470,NaN,57f837f1599be8a65248899206da5a2d4171799b3fd5ba...,84509376becf1aad68e11b815bece8fd22f2c2b41b9455...,AIS_AND_RADAR,2800,500,2025-08-20T06:33:43+00:00,1850,NaN,2800.0,400.0,NaN,249.0,4.669773,52.458736,10343720115976443926,2025-08-20T06:34:08.215690Z,False,NaN,NaN

In [55]:
vessels["sub-category"].unique()

<ArrowStringArray>
[                                        'Tug',
                          'Sail Training Ship',
                                           nan,
                               'Patrol Vessel',
                                 'Buoy Tender',
                    'Chemical/Products Tanker',
                            'Vehicles Carrier',
             'Passenger/Ro-Ro Ship (Vehicles)',
                          'General Cargo Ship',
                                'Bulk Carrier',
                                  'LPG Tanker',
             'Container Ship (Fully Cellular)',
                          'Crew/Supply Vessel',
                                'Pilot Vessel',
                                   'Crew Boat',
                    'Service Operation Vessel',
                              'Sailing Vessel',
                                       'Yacht',
                              'Fishing Vessel',
                            'Passenger/Cruise',
                              'Shuttle Tanker',
                              'Utility Vessel',
                      'Research Survey Vessel',
                              'Passenger Ship',
                      'Asphalt/Bitumen Tanker',
                            'Ro-Ro Cargo Ship',
                            'Crude Oil Tanker',
                             'Products Tanker',
                          'Work/Repair Vessel',
                                'Crane Vessel',
                       'Standby Safety Vessel',
             'Trailing Suction Hopper Dredger',
                           'Exhibition Vessel',
                                'Salvage Ship',
                               'Supply Tender',
                          'Museum, Stationary',
                      'Search & Rescue Vessel',
                       'Diving Support Vessel',
                   'Support Platform, jack up',
                          'Heavy Load Carrier',
            'Combination Gas Tanker (LNG/LPG)',
                       'Drilling Rig, jack up',
                        'Platform Supply Ship',
                     'Offshore Support Vessel',
 'Wind Turbine Installation Platform, jack up',
                             'Yacht (Sailing)',
                     'Water Injection Dredger',
                       'Molten Sulphur Tanker',
                     'Fishery Research Vessel',
                      'Anchor Handling Vessel',
                    'Pollution Control Vessel',
              'Replenishment Dry Cargo Vessel',
                             'Suction Dredger',
                   'Crude/Oil Products Tanker',
        'Heavy Load Carrier, semi submersible',
                      'Bunkering Tanker (LNG)',
                                  'LNG Tanker',
      'Commissioning Service Operation Vessel',
                                     'Frigate',
                              'Cement Carrier',
                  'Anchor Handling Tug Supply',
                               'Hopper, Motor',
                              'Command Vessel',
                                  'Minehunter',
             'Yacht Carrier, semi submersible',
                    'Refrigerated Cargo Ship ',
                       'Open Hatch Cargo Ship',
              'Bulk Carrier, Self-discharging',
                     'Pipe Layer Crane Vessel',
                  'Container/Ro-Ro Cargo Ship',
                          'Aggregates Carrier',
                       'Palletised Cargo Ship',
                           'Edible Oil Tanker',
      'Maintenance Platform, semi Submersible',
                       'Fishery Patrol Vessel']
Length: 75, dtype: str

In [54]:
vessels["hourminute"] = (
    pd.to_datetime(
        vessels["upload-timestamp"],
        utc=True,
        format="ISO8601"
    )
    .dt.tz_convert("Europe/Amsterdam")
    .dt.strftime("%H%M")
    .astype(int)
)

In [57]:
vessels[vessels["destination"] == "SAIL"]

,identifier-sensor,radar-length-cm,radar-beam-cm,position-x,position-y,speed-in-centimeters-per-second,x-speed,y-speed,orientation,significant-orientation,destination,pilot-on-board,track-number,imo-number,mmsi-number,eni-number,sensor-type,ais-length-cm,ais-beam-cm,update-time,type,sub-category,length,beam,port-role,short-term-avg-speed-in-cm-per-sec,lon,lat,id,upload-timestamp,oud_bericht,stale_since,name,hourminute
372,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:33:55+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:34:10.917449Z,False,NaN,NaN,834
428,12013,1900,400,124080.0,487586.0,0,0,0,0.3,NaN,SAIL,False,7177,NaN,01fa8c2dae86d17a6628054f8cb2d36fdee874a83e5492...,7e3ed78214a2a099cd584aee35fa8989ebc3efa8c89a39...,AIS,1900,400,2025-08-20T06:33:57+00:00,1850,NaN,2000.0,400.0,NaN,0.0,4.933140,52.375275,103621372668916818,2025-08-20T06:34:11.444133Z,False,NaN,NaN,834
3242,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:35:25+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:35:40.528445Z,False,NaN,NaN,835
3404,12013,1900,400,124080.0,487586.0,0,0,0,0.3,NaN,SAIL,False,7177,NaN,01fa8c2dae86d17a6628054f8cb2d36fdee874a83e5492...,7e3ed78214a2a099cd584aee35fa8989ebc3efa8c89a39...,AIS,1900,400,2025-08-20T06:35:30+00:00,1850,NaN,2000.0,400.0,NaN,0.0,4.933140,52.375275,103621372668916818,2025-08-20T06:35:41.821016Z,False,NaN,NaN,835
6186,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:36:55+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:37:14.979286Z,False,NaN,NaN,837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12638924,126666,2600,400,118194.0,492636.0,0,0,0,0.2,NaN,SAIL,False,11417,NaN,1a0442a1a66a9abbbb41b4f67153478b72cf63fabf1627...,840f9cd012e6a20bb526548dd0aa4a8a7be3a134131fe9...,AIS,2600,400,2025-08-24T08:58:16+00:00,1850,NaN,2600.0,400.0,NaN,0.0,4.846153,52.420297,18355331754560669296,2025-08-24T08:58:22.455642Z,False,NaN,OVING 1,1058
12638953,188614,1900,400,124085.0,487583.0,0,0,0,0.3,NaN,SAIL,False,14075,NaN,01fa8c2dae86d17a6628054f8cb2d36fdee874a83e5492...,7e3ed78214a2a099cd584aee35fa8989ebc3efa8c89a39...,AIS,1900,400,2025-08-24T08:58:17+00:00,1850,NaN,2000.0,400.0,NaN,0.0,4.933214,52.375248,103621372668916818,2025-08-24T08:58:22.628963Z,False,NaN,FRUITION,1058
12639665,182996,1300,200,124791.0,488014.0,60,57,-19,108.2,NaN,SAIL,False,5682,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS_AND_RADAR,0,0,2025-08-24T08:58:41+00:00,1850,NaN,2400.0,500.0,NaN,48.0,4.943542,52.379161,5627371271639895286,2025-08-24T08:58:43.288979Z,False,NaN,SPES,1058
12641689,182996,1400,200,124849.0,487998.0,100,99,-13,97.5,NaN,SAIL,False,5682,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS_AND_RADAR,0,0,2025-08-24T08:59:44+00:00,1850,NaN,2400.0,500.0,NaN,58.0,4.944396,52.379020,5627371271639895286,2025-08-24T08:59:46.332890Z,False,NaN,SPES,1059
12641756,126666,2600,400,118194.0,492636.0,0,0,0,0.2,NaN,SAIL,False,11417,NaN,1a0442a1a66a9abbbb41b4f67153478b72cf63fabf1627...,840f9cd012e6a20bb526548dd0aa4a8a7be3a134131fe9...,AIS,2600,400,2025-08-24T08:59:46+00:00,1850,NaN,2600.0,400.0,NaN,0.0,4.846153,52.420297,18355331754560669296,2025-08-24T08:59:48.327176Z,False,NaN,OVING 1,1059