In [1]:
import pandas as pd
import geopandas as gpd
from io import StringIO
import csv

# Data Loading

Change paths if needed to match your saved files.

In [2]:
SAIL2025_LVMA = pd.read_csv(r"C:\SAIL-Project\Data\SAIL2025_LVMA.csv")
sensor_location = pd.read_excel(r"C:\SAIL-Project\Data\sensor-location.xlsx")
vessels = pd.read_csv(r"C:\SAIL-Project\Data\Vesselposition_data_20-24Aug2025.csv")
tomtom = pd.read_csv(r"C:\SAIL-Project\Data\TomTom_data_20-24Aug2025.csv")
nwb_file = gpd.read_file(r"C:\SAIL-Project\Data\NWB_roads\NWB_roads\wegen_in_out.shp")

C:\Users\mateo\AppData\Local\Temp\ipykernel_22308\2430059984.py:3: DtypeWarning: Columns (32: name) have mixed types. Specify dtype option on import or set low_memory=False.
  vessels = pd.read_csv(r"C:\SAIL-Project\Data\Vesselposition_data_20-24Aug2025.csv")

# SAIL2025_LVMA

In [3]:
SAIL2025_LVMA.head(5)

,timestamp,CMSA-GAKH-01_0,CMSA-GAKH-01_180,CMSA-GAWW-11_120,CMSA-GAWW-11_300,CMSA-GAWW-12_115,CMSA-GAWW-12_295,CMSA-GAWW-13_120,CMSA-GAWW-13_300,CMSA-GAWW-14_40,...,GVCV-13_10,GVCV-13_190,GVCV-14_90,GVCV-14_270,hour,minute,day,month,weekday,is_weekend
0,2025-08-20 00:00:00+02:00,15,4,29,33,44,28,42,37,11,...,41,40,0,0,0,0,20,8,2,0
1,2025-08-20 00:03:00+02:00,1,3,21,29,34,39,9,14,6,...,0,0,0,0,0,3,20,8,2,0
2,2025-08-20 00:06:00+02:00,5,4,35,22,29,34,33,42,14,...,0,0,0,0,0,6,20,8,2,0
3,2025-08-20 00:09:00+02:00,4,4,40,47,42,40,19,34,15,...,0,0,0,0,0,9,20,8,2,0
4,2025-08-20 00:12:00+02:00,4,11,54,59,58,33,17,33,26,...,127,57,0,0,0,12,20,8,2,0

Based on README file, this DataFrame contains pedestrian crowd flow counts. Most columns are sensors.

In [4]:
SAIL2025_LVMA["timestamp"].size

2400

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
SAIL2025_LVMA.describe()

,CMSA-GAKH-01_0,CMSA-GAKH-01_180,CMSA-GAWW-11_120,CMSA-GAWW-11_300,CMSA-GAWW-12_115,CMSA-GAWW-12_295,CMSA-GAWW-13_120,CMSA-GAWW-13_300,CMSA-GAWW-14_40,CMSA-GAWW-14_220,CMSA-GAWW-15_30,CMSA-GAWW-15_210,CMSA-GAWW-16_30,CMSA-GAWW-16_210,CMSA-GAWW-17_40,CMSA-GAWW-17_220,CMSA-GAWW-19_115,CMSA-GAWW-19_295,CMSA-GAWW-20_120,CMSA-GAWW-20_300,CMSA-GAWW-21_120,CMSA-GAWW-21_300,CMSA-GAWW-23_109,CMSA-GAWW-23_289,GACM-04_50,GACM-04_230,GASA-01-A1_135,GASA-01-A1_315,GASA-01-A2_135,GASA-01-A2_315,GASA-01-B_135,GASA-01-B_315,GASA-01-C_135,GASA-01-C_315,GASA-02-01_135,GASA-02-01_315,GASA-02-02_135,GASA-02-02_315,GASA-03_105,GASA-03_285,GASA-04_135,GASA-04_315,GASA-05-O_135,GASA-05-O_315,GASA-05-W_135,GASA-05-W_315,GASA-06_95,GASA-06_275,GASA-06-B_95,GASA-06-B_275,GVCV-01_40,GVCV-01_220,GVCV-03_42,GVCV-03_222,GVCV-04_45,GVCV-04_225,GVCV-05-A_155,GVCV-05-A_335,GVCV-05-B_30,GVCV-05-B_210,GVCV-06_95,GVCV-06_275,GVCV-07_50,GVCV-07_230,GVCV-08_45,GVCV-08_225,GVCV-09_80,GVCV-09_260,GVCV-11_50,GVCV-11_230,GVCV-13_10,GVCV-13_190,GVCV-14_90,GVCV-14_270,hour,minute,day,month,weekday,is_weekend
count,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.00000,2400.00000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.0,2400.000000,2400.00
mean,57.513750,49.180000,37.840417,37.500417,39.021250,43.677500,20.566250,24.223333,17.682917,10.912083,25.784167,27.667083,31.23875,25.06875,23.668750,23.293333,34.465417,17.748333,24.972917,23.927083,58.222917,59.276667,8.055833,10.520000,53.148333,81.325833,10.286667,9.795417,28.301667,36.690833,12.271667,35.267083,27.609583,8.835833,15.065833,95.525000,126.797083,16.235417,110.038333,103.021667,64.394167,50.521667,17.455833,15.695417,15.971667,14.558750,0.001250,0.004167,4.695833,3.246667,12.857500,7.854583,24.338750,23.085000,21.938750,19.191250,17.906667,16.173750,17.583750,19.356250,7.391250,8.072500,6.209583,8.433750,4.374583,2.887083,0.023750,0.023333,30.751250,26.324167,32.629583,28.449583,24.782083,16.878750,11.500000,28.500000,22.000000,8.0,4.000000,0.40
std,69.204386,58.768898,36.631952,33.478431,34.266092,40.235263,24.612406,24.260349,16.685324,13.344451,28.954019,32.774489,33.65118,24.16050,22.823604,20.753536,32.638988,17.208042,28.269863,26.047094,50.850408,49.511462,8.574236,11.152343,47.832673,75.470229,13.687648,11.568787,29.047787,41.094299,15.272335,39.664484,34.049551,10.697152,26.771738,121.908521,146.770072,24.399362,124.482593,120.220245,64.901725,56.389991,22.848919,18.713615,23.324648,21.168016,0.035341,0.111749,13.794175,9.120790,26.865087,16.931245,42.988747,46.547813,42.007929,41.697651,52.999898,33.729056,36.558057,53.550708,25.732355,27.696032,20.133647,27.738698,13.043076,11.734175,0.232469,0.226149,78.573926,58.907717,67.133867,53.724243,57.345319,35.979428,6.923629,17.302449,1.414508,0.0,1.414508,0.49
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.000000,8.0,2.000000,0.00
25%,3.000000,2.000000,6.000000,6.000000,7.000000,7.000000,3.000000,4.000000,3.000000,2.000000,3.000000,3.000000,5.00000,4.00000,3.000000,4.000000,4.000000,3.000000,0.000000,1.000000,8.000000,9.000000,2.000000,2.000000,10.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2.000000,1.000000,7.000000,4.000000,4.000000,3.000000,1.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.750000,14.250000,21.000000,8.0,3.000000,0.00
50%,17.000000,15.000000,30.000000,32.000000,32.000000,36.000000,12.000000,17.000000,13.000000,7.000000,15.000000,16.000000,21.00000,19.00000,17.000000,20.000000,27.000000,14.000000,11.000000,13.000000,49.000000,55.000000,5.000000,7.000000,40.000000,65.000000,5.000000,5.000000,21.000000,25.000000,7.000000,24.000000,14.000000,6.000000,6.000000,19.500000,57.500000,6.000000,49.500000,35.500000,48.500000,31.000000,12.000000,13.000000,11.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,11.500000,28.500000,22.000000,8.0,4.000000,0.00
75%,110.250000,95.000000,59.000000,61.000000,62.000000,68.000000,28.000000,37.000000,28.000000,15.000000,40.000000,39.000000,44.00000,39.00000,40.000000,37.000000,56.000000,28.000000,47.000000,44.000000,103.000000,99.000000,12.000000,16.000000,89.000000,144.000000,17.000000,17.000000,51.000000,62.000000,19.000000,56.250000,43.000000,13.000000,17.250000,184.250000,226.000000,20.000000,204.000000,194.000000,110.000000,83.000000,25.000000,22.000000,20.000000,19.000000,0.000000,0.000000,2.000000,2.000000,9.000000,6.000000,31.000000,19.000000,25.000000,8.000000,3.000000,15.000000,16.000000,3.000000,0.250000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,15.250000,26.000000,35.000000,7.000000,17.000000,17.250000,42.750000,23.000000,8.0,5.000000,1.00
max,266.000000,257.000000,246.000000,156.000000,168.000000,230.000000,166.000000,124.000000,123.000000,141.000000,188.000000,212.000000,218.00000,148.00000,123.000000,114.000000,167.000000,93.000000,140.000000,137.000000,225.000000,387.000000,61.000000,120.000000,212.000000,318.000000,129.000000,83.000000,134.000000,263.000000,115.000000,291.000000,211.000000,114.000000,253.000000,588.000000,599.000000,200.000000,542.000000,718.000000,291.000000,362.000000,205.000000,160.000000,249.000000,192.000000,1.000000,4.000000,164.000000,83.000000,173.000000,133.000000,249.000000,284.000000,261.000000,280.000000,424.000000,245.000000,303.000000,362.000000,262.000000,287.000000,168.000000,268.000000,117.000000,326.000000,4.000000,4.000000,528.000000,396.000000,396.000000,339.000000,381.000000,280.000000,23.000000,57.000000,24.000000,8.0,6.000000,1.00

Depending on the day, the hours of the SAIL event vary. We create masks to keep rows that only measure during these hours. When joining the columns we realized that some rows had hours or minutes without 2 digits. For example, 04:05 was 4 in column hour and 5 in column minute. We had to change this for the masks.

In [7]:
SAIL2025_LVMA["hourminute"] = (SAIL2025_LVMA["hour"].astype(str).str.zfill(2) + SAIL2025_LVMA["minute"].astype(str).str.zfill(2))
SAIL2025_LVMA["hourminute"] = SAIL2025_LVMA["hourminute"].astype(int)

In [8]:
wen = (SAIL2025_LVMA["day"] == 20) & (SAIL2025_LVMA["hourminute"] >= 1000) & (SAIL2025_LVMA["hourminute"] <= 2245)
thu = (SAIL2025_LVMA["day"] == 21) & (SAIL2025_LVMA["hourminute"] >= 800) & (SAIL2025_LVMA["hourminute"] <= 2245)
fri = (SAIL2025_LVMA["day"] == 22) & (SAIL2025_LVMA["hourminute"] >= 900) & (SAIL2025_LVMA["hourminute"] <= 2245)
sat = (SAIL2025_LVMA["day"] == 23) & (SAIL2025_LVMA["hourminute"] >= 900) & (SAIL2025_LVMA["hourminute"] <= 2245)
sun = (SAIL2025_LVMA["day"] == 24) & (SAIL2025_LVMA["hourminute"] >= 900) & (SAIL2025_LVMA["hourminute"] <= 2100)

In [9]:
filtered = SAIL2025_LVMA[wen | thu | fri | sat | sun]
len(filtered.index)

1345

Making this filters we get roughly 1000 rows less compared to the original dataframe.

In [10]:
filtered.isna().sum().sum() # No missing values

np.int64(0)

Now check if there are zero value readings in any sensors during this period to detect malfunctions.

In [11]:
for column in filtered.columns:

    temp = filtered[filtered[column] == 0]
    print(f"{column} - {len(temp.index)}")

timestamp - 0
CMSA-GAKH-01_0 - 6
CMSA-GAKH-01_180 - 6
CMSA-GAWW-11_120 - 4
CMSA-GAWW-11_300 - 4
CMSA-GAWW-12_115 - 8
CMSA-GAWW-12_295 - 4
CMSA-GAWW-13_120 - 37
CMSA-GAWW-13_300 - 23
CMSA-GAWW-14_40 - 12
CMSA-GAWW-14_220 - 27
CMSA-GAWW-15_30 - 32
CMSA-GAWW-15_210 - 19
CMSA-GAWW-16_30 - 9
CMSA-GAWW-16_210 - 17
CMSA-GAWW-17_40 - 12
CMSA-GAWW-17_220 - 5
CMSA-GAWW-19_115 - 11
CMSA-GAWW-19_295 - 26
CMSA-GAWW-20_120 - 294
CMSA-GAWW-20_300 - 292
CMSA-GAWW-21_120 - 24
CMSA-GAWW-21_300 - 29
CMSA-GAWW-23_109 - 35
CMSA-GAWW-23_289 - 34
GACM-04_50 - 0
GACM-04_230 - 0
GASA-01-A1_135 - 56
GASA-01-A1_315 - 63
GASA-01-A2_135 - 33
GASA-01-A2_315 - 31
GASA-01-B_135 - 22
GASA-01-B_315 - 8
GASA-01-C_135 - 17
GASA-01-C_315 - 29
GASA-02-01_135 - 75
GASA-02-01_315 - 91
GASA-02-02_135 - 62
GASA-02-02_315 - 103
GASA-03_105 - 0
GASA-03_285 - 1
GASA-04_135 - 0
GASA-04_315 - 0
GASA-05-O_135 - 5
GASA-05-O_315 - 1
GASA-05-W_135 - 1
GASA-05-W_315 - 5
GASA-06_95 - 1345
GASA-06_275 - 1345
GASA-06-B_95 - 663
GASA-06-B_275 - 647
GVCV-01_40 - 535
GVCV-01_220 - 552
GVCV-03_42 - 411
GVCV-03_222 - 409
GVCV-04_45 - 541
GVCV-04_225 - 558
GVCV-05-A_155 - 551
GVCV-05-A_335 - 480
GVCV-05-B_30 - 491
GVCV-05-B_210 - 536
GVCV-06_95 - 894
GVCV-06_275 - 854
GVCV-07_50 - 944
GVCV-07_230 - 959
GVCV-08_45 - 903
GVCV-08_225 - 955
GVCV-09_80 - 1321
GVCV-09_260 - 1321
GVCV-11_50 - 549
GVCV-11_230 - 478
GVCV-13_10 - 564
GVCV-13_190 - 530
GVCV-14_90 - 544
GVCV-14_270 - 509
hour - 0
minute - 69
day - 0
month - 0
weekday - 0
is_weekend - 828
hourminute - 0

In [12]:
filtered[filtered["GVCV-09_80"] != 0]

,timestamp,CMSA-GAKH-01_0,CMSA-GAKH-01_180,CMSA-GAWW-11_120,CMSA-GAWW-11_300,CMSA-GAWW-12_115,CMSA-GAWW-12_295,CMSA-GAWW-13_120,CMSA-GAWW-13_300,CMSA-GAWW-14_40,CMSA-GAWW-14_220,CMSA-GAWW-15_30,CMSA-GAWW-15_210,CMSA-GAWW-16_30,CMSA-GAWW-16_210,CMSA-GAWW-17_40,CMSA-GAWW-17_220,CMSA-GAWW-19_115,CMSA-GAWW-19_295,CMSA-GAWW-20_120,CMSA-GAWW-20_300,CMSA-GAWW-21_120,CMSA-GAWW-21_300,CMSA-GAWW-23_109,CMSA-GAWW-23_289,GACM-04_50,GACM-04_230,GASA-01-A1_135,GASA-01-A1_315,GASA-01-A2_135,GASA-01-A2_315,GASA-01-B_135,GASA-01-B_315,GASA-01-C_135,GASA-01-C_315,GASA-02-01_135,GASA-02-01_315,GASA-02-02_135,GASA-02-02_315,GASA-03_105,GASA-03_285,GASA-04_135,GASA-04_315,GASA-05-O_135,GASA-05-O_315,GASA-05-W_135,GASA-05-W_315,GASA-06_95,GASA-06_275,GASA-06-B_95,GASA-06-B_275,GVCV-01_40,GVCV-01_220,GVCV-03_42,GVCV-03_222,GVCV-04_45,GVCV-04_225,GVCV-05-A_155,GVCV-05-A_335,GVCV-05-B_30,GVCV-05-B_210,GVCV-06_95,GVCV-06_275,GVCV-07_50,GVCV-07_230,GVCV-08_45,GVCV-08_225,GVCV-09_80,GVCV-09_260,GVCV-11_50,GVCV-11_230,GVCV-13_10,GVCV-13_190,GVCV-14_90,GVCV-14_270,hour,minute,day,month,weekday,is_weekend,hourminute
350,2025-08-20 17:30:00+02:00,159,135,61,67,53,45,10,29,21,10,31,27,16,16,56,57,28,28,62,44,133,88,1,19,92,176,16,31,29,78,60,96,29,12,44,214,318,43,242,114,122,149,154,115,191,123,0,0,1,4,0,0,0,0,0,0,3,114,7,5,0,110,0,0,51,1,2,0,183,17,52,2,88,4,17,30,20,8,2,0,1730
362,2025-08-20 18:06:00+02:00,165,121,90,45,99,47,37,34,34,8,27,27,45,32,46,65,18,16,65,80,109,96,4,13,57,99,14,11,26,30,11,41,47,5,38,127,165,56,118,138,94,64,23,40,54,37,0,0,50,8,0,0,4,133,0,0,205,78,2,1,1,108,2,1,0,0,1,0,88,243,58,7,0,0,18,6,20,8,2,0,1806
377,2025-08-20 18:51:00+02:00,91,69,62,51,52,74,12,26,26,7,17,10,47,32,44,26,36,27,71,68,121,88,6,15,72,82,23,1,25,57,6,18,11,24,29,173,189,36,120,78,92,50,46,21,52,52,0,0,0,0,50,21,5,0,20,0,218,117,0,202,0,0,0,5,76,46,2,1,1,1,0,0,0,0,18,51,20,8,2,0,1851
391,2025-08-20 19:33:00+02:00,62,35,64,57,71,34,22,39,13,12,27,47,37,27,45,41,53,24,87,59,162,62,9,6,101,88,22,37,30,32,23,69,127,8,25,159,272,49,131,222,89,87,27,36,54,81,0,0,3,3,1,11,0,0,47,4,0,0,0,0,0,0,0,0,2,2,1,2,2,0,0,0,1,48,19,33,20,8,2,0,1933
408,2025-08-20 20:24:00+02:00,60,36,65,106,81,51,32,51,24,11,16,42,42,26,57,33,74,17,39,50,97,74,30,18,82,111,24,20,46,51,4,27,46,22,12,169,167,41,92,196,66,81,3,16,8,10,0,0,38,4,48,33,28,3,0,0,0,0,41,12,3,0,0,0,43,36,3,0,0,0,0,0,152,35,20,24,20,8,2,0,2024
415,2025-08-20 20:45:00+02:00,44,28,91,77,76,72,50,60,41,23,66,49,54,40,50,32,71,34,72,40,102,104,24,26,93,119,28,27,72,67,11,36,18,24,10,149,146,61,125,219,72,56,21,15,13,34,0,0,3,29,0,0,82,0,0,0,22,33,0,0,0,63,0,0,0,0,4,4,1,3,0,0,1,33,20,45,20,8,2,0,2045
420,2025-08-20 21:00:00+02:00,23,23,61,80,81,125,27,74,27,12,69,64,100,65,55,33,97,35,47,30,117,99,16,23,91,70,14,19,53,66,20,16,22,12,15,184,142,29,89,203,46,74,7,11,8,12,0,0,1,3,51,33,0,0,0,0,1,23,0,1,2,0,3,0,8,0,1,1,0,0,105,1,4,13,21,0,20,8,2,0,2100
689,2025-08-21 10:27:00+02:00,19,34,5,6,13,27,2,0,10,2,0,6,12,6,10,13,12,23,18,15,44,36,5,5,23,74,6,13,36,32,11,25,15,12,12,14,333,3,248,24,141,7,19,17,14,6,0,0,0,0,0,0,0,101,35,1,94,10,11,0,0,0,0,3,3,0,1,1,0,0,0,0,74,45,10,27,21,8,3,0,1027
892,2025-08-21 20:36:00+02:00,99,32,98,50,89,108,46,72,40,13,48,46,95,51,40,66,95,40,77,44,85,105,23,25,69,61,23,13,12,57,1,15,3,10,17,170,114,9,144,85,27,45,21,9,11,11,0,0,0,1,0,0,0,2,2,3,0,1,77,1,0,0,0,0,0,0,3,0,30,2,0,0,116,30,20,36,21,8,3,0,2036
893,2025-08-21 20:39:00+02:00,82,50,84,76,87,84,37,47,67,8,50,78,56,39,47,56,80,60,64,55,104,117,10,20,94,61,19,17,35,34,28,45,39,11,14,183,129,31,157,154,68,68,7,14,10,2,0,0,0,0,0,0,104,209,0,0,0,0,44,1,0,0,0,0,0,0,3,3,213,163,0,0,4,106,20,39,21,8,3,0,2039
1281,2025-08-22 16:03:00+02:00,158,173,57,57,60,29,19,13,25,22,28,12,32,27,44,17,46,24,59,69,104,105,11,10,86,135,12,46,59,63,18,52,4,10,29,224,381,4,350,331,157,84,36,37,33,31,0,0,21,1,0,0,1,0,49,4,170,1,21,0,101,0,111,34,58,20,1,2,0,3,208,76,1,22,16,3,22,8,4,0,1603
1282,2025-08-22 16:06:00+02:00,164,184,43,140,58,76,13,21,16,26,38,27,17,25,30,32,46,65,52,66,99,82,15,17,110,240,22,29,28,72,15,93,6,11,17,391,319,8,363,291,150,77,39,29,19,26,0,0,16,1,7,1,1,1,0,0,105,103,0,0,68,1,1,0,0,0,1,0,202,0,3,127,0,0,16,6,22,8,4,0,1606
1283,2025-08-22 16:09:00+02:00,200,109,45,75,57,108,8,55,9,21,2,23,21,148,18,75,57,46,64,137,54,259,7,120,162,172,24,19,40,54,22,28,24,16,4,326,306,6,295,291,122,147,6,26,3,12,0,0,46,3,6,0,0,221,0,0,7,49,1,170,0,3,0,0,0,0,3,2,172,171,0,0,205,7,16,9,22,8,4,0,1609
1387,2025-08-22 21:21:00+02:00,31,10,108,82,113,90,93,36,35,10,95,123,99,120,44,21,98,50,85,58,130,69,14,21,117,84,28,19,62,54,17,23,38,9,4,186,259,4,145,159,89,60,5,9,16,9,0,0,33,3,0,0,63,44,23,0,16,31,1,224,0,0,13,32,14,3,2,3,0,10,0,45,0,0,21,21,22,8,4,0,2121
1716,2025-08-23 13:48:00+02:00,94,81,39,48,29,44,12,15,9,2,16,11,20,10,24,34,18,22,37,43,127,82,3,11,95,208,23,21,82,111,49,86,93,18,103,215,538,7,361,252,203,102,25,13,26,23,0,0,7,2,50,2,6,5,72,9,5,95,0,0,0,4,0,0,79,11,2,2,367,69,0,0,269,55,13,48,23,8,5,1,1348
1782,2025-08-23 17:06:00+02:00,206,188,81,102,110,93,27,48,70,29,47,34,42,46,63,70,94,26,75,93,140,192,17,20,169,258,23,42,67,108,25,154,45,41,33,388,526,1,310,426,224,310,24,33,17,27,0,0,0,41,6,30,85,152,0,0,0,2,3,138,54,1,90,119,0,0,1,1,183,197,112,110,246,54,17,6,23,8,5,1,1706
1783,2025-08-23 17:09:00+02:00,138,112,75,59,63,55,18,22,25,13,38,42,35,30,49,36,43,26,72,55,98,125,3,3,172,255,38,34,56,81,38,82,77,34,32,453,454,8,297,403,150,159,35,40,24,25,0,0,3,28,76,18,129,18,0,0,119,3,183,303,228,2,46,3,42,39,1,1,3,175,3,178,1,197,17,9,23,8,5,1,1709
1784,2025-08-23 17:12:00+02:00,233,186,66,53,80,94,36,39,39,15,62,49,50,36,56,89,109,30,78,58,177,131,13,16,188,202,31,39,48,99,22,111,96,22,11,508,486,20,235,394,223,156,11,32,17,30,0,0,0,8,7,8,1,6,0,0,169,117,133,2,114,6,2,2,3,0,1,0,0,0,0,2,0,8,17,12,23,8,5,1,1712
1803,2025-08-23 18:09:00+02:00,223,144,97,72,131,98,30,48,53,28,62,51,49,70,74,68,96,24,78,88,169,132,16,22,72,176,56,18,74,103,83,100,114,7,30,397,514,7,182,348,150,213,31,15,13,41,0,0,103,3,41,7,1,0,5,194,92,0,12,0,0,0,0,0,19,1,2,0,0,0,0,0,284,3,18,9,23,8,5,1,1809
1813,2025-08-23 18:39:00+02:00,129,72,69,59,53,57,13,45,32,17,47,40,68,25,42,19,57,26,50,44,99,87,11,11,144,128,60,25,78,60,34,57,132,5,19,331,327,4,247,343,127,228,25,10,17,23,0,0,0,0,13,9,0,0,140,74,212,0,0,0,75,3,43,163,6,30,3,3,4,271,0,0,272,9,18,39,23,8,5,1,1839
2143,2025-08-24 11:09:00+02:00,23,39,26,5,8,11,8,5,21,0,15,2,7,13,11,22,10,7,0,0,28,26,11,14,29,122,17,9,38,86,13,21,11,6,54,41,428,4,440,51,142,50,17,19,15,18,0,0,0,0,0,0,4,79,7,2,3,22,3,116,0,0,0,0,0,4,2,0,97,3,0,0,0,54,11,9,24,8,6,1,1109
2144,2025-08-24 11:12:00+02:00,27,61,13,17,17,36,1,5,3,21,14,10,7,20,11,13,7,8,0,0,55,68,8,4,43,127,10,17,47,37,16,15,15,9,17,52,230,1,248,28,77,19,8,8,8,5,0,0,29,2,36,10,33,14,0,0,2,0,56,1,96,33,0,0,0,2,1,2,119,99,51,0,2,41,11,12,24,8,6,1,1112
2146,2025-08-24 11:18:00+02:00,44,55,22,14,12,14,2,13,9,4,11,9,8,15,11,15,14,3,0,0,52,59,4,9,39,122,32,19,70,59,22,50,31,4,33,61,353,1,368,86,128,27,12,17,17,11,0,0,12,4,16,1,0,0,60,75,70,1,7,2,0,1,0,46,0,0,1,2,2,2,0,48,1,0,11,18,24,8,6,1,1118
2167,2025-08-24 12:21:00+02:00,95,102,23,26,42,27,4,19,19,8,8,8,25,21,12,13,31,11,0,0,66,77,5,2,52,188,29,19,44,82,68,55,17,15,24,83,275,4,194,82,174,107,18,9,13,23,0,0,0,0,100,10,0,2,16,0,0,2,104,2,0,0,33,65,0,0,2,0,0,2,0,4,227,2,12,21,24,8,6,1,1221

# sensor-location

In [13]:
sensor_location.head(5)

,Objectummer,Locatienaam,Lat/Long,Breedte,Effectieve breedte
0,CMSA-GAKH-01,Kalverstraat t.h.v. 1,"52.372634, 4.892071",8,"6,7"
1,CMSA-GAWW-11,Korte Niezel,"52.374616, 4.899830","3,8","3,4"
2,CMSA-GAWW-12,Oudekennissteeg,"52.373860, 4.898690",3,"2,6"
3,CMSA-GAWW-13,Stoofsteeg,"52.372439, 4.897689","2,6","2,2"
4,CMSA-GAWW-14,Oudezijds Voorburgwal t.h.v. 91,"52.373538, 4.898166",4,"3,6"

- Objectummer - Censor name
- Locatienaam - Location name
- Lat/Long - Coordinates of censor
- Breedte - Sensor width
- Effective breedte - Effective width of the censor.

In [14]:
sensor_location[['Latitude', 'Longitude']] = sensor_location["Lat/Long"].str.split(",", expand=True).astype(float)

sensor_location.head()

,Objectummer,Locatienaam,Lat/Long,Breedte,Effectieve breedte,Latitude,Longitude
0,CMSA-GAKH-01,Kalverstraat t.h.v. 1,"52.372634, 4.892071",8,"6,7",52.372634,4.892071
1,CMSA-GAWW-11,Korte Niezel,"52.374616, 4.899830","3,8","3,4",52.374616,4.899830
2,CMSA-GAWW-12,Oudekennissteeg,"52.373860, 4.898690",3,"2,6",52.373860,4.898690
3,CMSA-GAWW-13,Stoofsteeg,"52.372439, 4.897689","2,6","2,2",52.372439,4.897689
4,CMSA-GAWW-14,Oudezijds Voorburgwal t.h.v. 91,"52.373538, 4.898166",4,"3,6",52.373538,4.898166

In [15]:
sensor_location = sensor_location[["Objectummer", "Latitude", "Longitude"]]

sensor_location.head(5)

    Objectummer   Latitude  Longitude
0  CMSA-GAKH-01  52.372634   4.892071
1  CMSA-GAWW-11  52.374616   4.899830
2  CMSA-GAWW-12  52.373860   4.898690
3  CMSA-GAWW-13  52.372439   4.897689
4  CMSA-GAWW-14  52.373538   4.898166

# Vesselposition

In [16]:
len(vessels.columns)

33

In [17]:
len(vessels.index)

12641979

There are more than 12 million columns, so we will start working with filters to make data more managable.

In [18]:
vessels.head()

,identifier-sensor,radar-length-cm,radar-beam-cm,position-x,position-y,speed-in-centimeters-per-second,x-speed,y-speed,orientation,significant-orientation,destination,pilot-on-board,track-number,imo-number,mmsi-number,eni-number,sensor-type,ais-length-cm,ais-beam-cm,update-time,type,sub-category,length,beam,port-role,short-term-avg-speed-in-cm-per-sec,lon,lat,id,upload-timestamp,oud_bericht,stale_since,name
0,251,2500,1200,100561.0,497650.0,30,-15,-26,209.9,NaN,HARBOUR ASSISTING,False,4450,745900ce09e5bcd3ad26ca148ed421298442f6f29a29ef...,4e73147932245214a49503c66d37ccb8e04dc06299fbf5...,NaN,AIS_AND_RADAR,2500,1200,2025-08-20T06:33:43+00:00,TUG,Tug,2500.0,1100.0,TUG_VESSEL,97.0,4.586152,52.463890,14523957174087988532,2025-08-20T06:34:08.177626Z,False,NaN,NaN
1,13212,2000,600,100329.0,497504.0,160,-151,53,289.5,NaN,NaN,False,8870,cff0a521594265f8f2858910679298ebaccda2b18785dc...,dfb315a6b5cff224394af277e0053d057db332a988ccc3...,NaN,AIS,1800,800,2025-08-20T06:33:43+00:00,YACHT,Sail Training Ship,2000.0,600.0,NaN,165.0,4.582762,52.462554,8410171728078482327,2025-08-20T06:34:08.181693Z,False,NaN,NaN
2,390,3300,1200,106036.0,498034.0,0,0,0,0.1,0.1,VELSEN,False,11964,2869e3dc53f76fb9395592febec8615c89ca36c7078b97...,0d11ea82dff9438409d2a9f3416802933496c659a0fa84...,NaN,AIS,3300,1200,2025-08-20T06:33:43+00:00,TUG,Tug,3300.0,1200.0,NaN,0.0,4.666652,52.467857,15111480980279746939,2025-08-20T06:34:08.196046Z,False,NaN,NaN
3,392,3600,800,105998.0,497971.0,0,0,0,0.1,0.1,AMSTERDAM,False,3644,NaN,e324f61d2312f715bfa3a70729570922528bcb0172e58c...,65d3845c259199b415346456c03b004d55c9bb2b6db69d...,AIS,3400,800,2025-08-20T06:33:43+00:00,8490,NaN,3400.0,700.0,NaN,0.0,4.666102,52.467288,8852227552724661228,2025-08-20T06:34:08.200039Z,False,NaN,NaN
4,10247,2000,300,106238.0,497017.0,240,-196,138,305.2,NaN,AMSTERDAM,False,11470,NaN,57f837f1599be8a65248899206da5a2d4171799b3fd5ba...,84509376becf1aad68e11b815bece8fd22f2c2b41b9455...,AIS_AND_RADAR,2800,500,2025-08-20T06:33:43+00:00,1850,NaN,2800.0,400.0,NaN,249.0,4.669773,52.458736,10343720115976443926,2025-08-20T06:34:08.215690Z,False,NaN,NaN

In [19]:
vessels["sub-category"].unique() # Many types here so it will be difficult to determine which ones go to SAIL

<ArrowStringArray>
[                                        'Tug',
                          'Sail Training Ship',
                                           nan,
                               'Patrol Vessel',
                                 'Buoy Tender',
                    'Chemical/Products Tanker',
                            'Vehicles Carrier',
             'Passenger/Ro-Ro Ship (Vehicles)',
                          'General Cargo Ship',
                                'Bulk Carrier',
                                  'LPG Tanker',
             'Container Ship (Fully Cellular)',
                          'Crew/Supply Vessel',
                                'Pilot Vessel',
                                   'Crew Boat',
                    'Service Operation Vessel',
                              'Sailing Vessel',
                                       'Yacht',
                              'Fishing Vessel',
                            'Passenger/Cruise',
                              'Shuttle Tanker',
                              'Utility Vessel',
                      'Research Survey Vessel',
                              'Passenger Ship',
                      'Asphalt/Bitumen Tanker',
                            'Ro-Ro Cargo Ship',
                            'Crude Oil Tanker',
                             'Products Tanker',
                          'Work/Repair Vessel',
                                'Crane Vessel',
                       'Standby Safety Vessel',
             'Trailing Suction Hopper Dredger',
                           'Exhibition Vessel',
                                'Salvage Ship',
                               'Supply Tender',
                          'Museum, Stationary',
                      'Search & Rescue Vessel',
                       'Diving Support Vessel',
                   'Support Platform, jack up',
                          'Heavy Load Carrier',
            'Combination Gas Tanker (LNG/LPG)',
                       'Drilling Rig, jack up',
                        'Platform Supply Ship',
                     'Offshore Support Vessel',
 'Wind Turbine Installation Platform, jack up',
                             'Yacht (Sailing)',
                     'Water Injection Dredger',
                       'Molten Sulphur Tanker',
                     'Fishery Research Vessel',
                      'Anchor Handling Vessel',
                    'Pollution Control Vessel',
              'Replenishment Dry Cargo Vessel',
                             'Suction Dredger',
                   'Crude/Oil Products Tanker',
        'Heavy Load Carrier, semi submersible',
                      'Bunkering Tanker (LNG)',
                                  'LNG Tanker',
      'Commissioning Service Operation Vessel',
                                     'Frigate',
                              'Cement Carrier',
                  'Anchor Handling Tug Supply',
                               'Hopper, Motor',
                              'Command Vessel',
                                  'Minehunter',
             'Yacht Carrier, semi submersible',
                    'Refrigerated Cargo Ship ',
                       'Open Hatch Cargo Ship',
              'Bulk Carrier, Self-discharging',
                     'Pipe Layer Crane Vessel',
                  'Container/Ro-Ro Cargo Ship',
                          'Aggregates Carrier',
                       'Palletised Cargo Ship',
                           'Edible Oil Tanker',
      'Maintenance Platform, semi Submersible',
                       'Fishery Patrol Vessel']
Length: 75, dtype: str

Create an hour time column which will be useful for later filtering on the dashboard.

In [20]:
vessels["hourminute"] = (
    pd.to_datetime(
        vessels["upload-timestamp"],
        utc=True,
        format="ISO8601"
    )
    .dt.tz_convert("Europe/Amsterdam")
    .dt.strftime("%H%M")
    .astype(int)
)

Trying to filter the dataframe using SAIL as a destination turned out to be useful.

In [21]:
SAIL_destination = vessels[vessels["destination"] == "SAIL"]

SAIL_destination

,identifier-sensor,radar-length-cm,radar-beam-cm,position-x,position-y,speed-in-centimeters-per-second,x-speed,y-speed,orientation,significant-orientation,destination,pilot-on-board,track-number,imo-number,mmsi-number,eni-number,sensor-type,ais-length-cm,ais-beam-cm,update-time,type,sub-category,length,beam,port-role,short-term-avg-speed-in-cm-per-sec,lon,lat,id,upload-timestamp,oud_bericht,stale_since,name,hourminute
372,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:33:55+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:34:10.917449Z,False,NaN,NaN,834
428,12013,1900,400,124080.0,487586.0,0,0,0,0.3,NaN,SAIL,False,7177,NaN,01fa8c2dae86d17a6628054f8cb2d36fdee874a83e5492...,7e3ed78214a2a099cd584aee35fa8989ebc3efa8c89a39...,AIS,1900,400,2025-08-20T06:33:57+00:00,1850,NaN,2000.0,400.0,NaN,0.0,4.933140,52.375275,103621372668916818,2025-08-20T06:34:11.444133Z,False,NaN,NaN,834
3242,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:35:25+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:35:40.528445Z,False,NaN,NaN,835
3404,12013,1900,400,124080.0,487586.0,0,0,0,0.3,NaN,SAIL,False,7177,NaN,01fa8c2dae86d17a6628054f8cb2d36fdee874a83e5492...,7e3ed78214a2a099cd584aee35fa8989ebc3efa8c89a39...,AIS,1900,400,2025-08-20T06:35:30+00:00,1850,NaN,2000.0,400.0,NaN,0.0,4.933140,52.375275,103621372668916818,2025-08-20T06:35:41.821016Z,False,NaN,NaN,835
6186,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:36:55+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:37:14.979286Z,False,NaN,NaN,837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12638924,126666,2600,400,118194.0,492636.0,0,0,0,0.2,NaN,SAIL,False,11417,NaN,1a0442a1a66a9abbbb41b4f67153478b72cf63fabf1627...,840f9cd012e6a20bb526548dd0aa4a8a7be3a134131fe9...,AIS,2600,400,2025-08-24T08:58:16+00:00,1850,NaN,2600.0,400.0,NaN,0.0,4.846153,52.420297,18355331754560669296,2025-08-24T08:58:22.455642Z,False,NaN,OVING 1,1058
12638953,188614,1900,400,124085.0,487583.0,0,0,0,0.3,NaN,SAIL,False,14075,NaN,01fa8c2dae86d17a6628054f8cb2d36fdee874a83e5492...,7e3ed78214a2a099cd584aee35fa8989ebc3efa8c89a39...,AIS,1900,400,2025-08-24T08:58:17+00:00,1850,NaN,2000.0,400.0,NaN,0.0,4.933214,52.375248,103621372668916818,2025-08-24T08:58:22.628963Z,False,NaN,FRUITION,1058
12639665,182996,1300,200,124791.0,488014.0,60,57,-19,108.2,NaN,SAIL,False,5682,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS_AND_RADAR,0,0,2025-08-24T08:58:41+00:00,1850,NaN,2400.0,500.0,NaN,48.0,4.943542,52.379161,5627371271639895286,2025-08-24T08:58:43.288979Z,False,NaN,SPES,1058
12641689,182996,1400,200,124849.0,487998.0,100,99,-13,97.5,NaN,SAIL,False,5682,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS_AND_RADAR,0,0,2025-08-24T08:59:44+00:00,1850,NaN,2400.0,500.0,NaN,58.0,4.944396,52.379020,5627371271639895286,2025-08-24T08:59:46.332890Z,False,NaN,SPES,1059
12641756,126666,2600,400,118194.0,492636.0,0,0,0,0.2,NaN,SAIL,False,11417,NaN,1a0442a1a66a9abbbb41b4f67153478b72cf63fabf1627...,840f9cd012e6a20bb526548dd0aa4a8a7be3a134131fe9...,AIS,2600,400,2025-08-24T08:59:46+00:00,1850,NaN,2600.0,400.0,NaN,0.0,4.846153,52.420297,18355331754560669296,2025-08-24T08:59:48.327176Z,False,NaN,OVING 1,1059

However, this might not be all the rows corresponding to vessel position as boats will have SAIL as a destination when they are going there only. They might not have this destination once the arrive and start moving/leaving.

"track-number" seems to identify a unique vessel. To confirm this, we grab the first unique value and filter the original dataframe.

In [22]:
SAIL_destination["track-number"].unique()

array([13659,  7177,  6977, ...,  5671,  5983,  5682], shape=(1268,))

In [23]:
vessels[vessels["track-number"]==(SAIL_destination["track-number"].unique()[0])]

,identifier-sensor,radar-length-cm,radar-beam-cm,position-x,position-y,speed-in-centimeters-per-second,x-speed,y-speed,orientation,significant-orientation,destination,pilot-on-board,track-number,imo-number,mmsi-number,eni-number,sensor-type,ais-length-cm,ais-beam-cm,update-time,type,sub-category,length,beam,port-role,short-term-avg-speed-in-cm-per-sec,lon,lat,id,upload-timestamp,oud_bericht,stale_since,name,hourminute
372,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:33:55+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:34:10.917449Z,False,NaN,NaN,834
3242,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:35:25+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:35:40.528445Z,False,NaN,NaN,835
6186,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:36:55+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:37:14.979286Z,False,NaN,NaN,837
9061,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:38:25+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:38:40.429858Z,False,NaN,NaN,838
12048,705,2400,500,105646.0,498873.0,0,0,0,0.1,0.1,SAIL,False,13659,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS,0,0,2025-08-20T06:39:58+00:00,1850,NaN,2400.0,500.0,NaN,1.0,4.660789,52.475362,5627371271639895286,2025-08-20T06:40:11.397253Z,False,NaN,NaN,840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11065929,159673,2000,400,123320.0,487852.0,150,140,-55,111.5,NaN,AMSTERDAM,False,13659,NaN,1ae7ae72f35cc5f64bbc756158374d26bf08ca5a357ab5...,7956c52f6a2cb2a5fcb461a8d752074bfadc811ef4efe7...,AIS_AND_RADAR,2000,400,2025-08-23T15:45:26+00:00,1850,NaN,1900.0,400.0,NaN,129.0,4.921955,52.377622,13014290783095305671,2025-08-23T15:45:34.412344Z,False,NaN,DE TIJD ZAL T LEREN,1745
11066289,159673,2000,400,123324.0,487849.0,150,140,-55,111.5,NaN,AMSTERDAM,False,13659,NaN,1ae7ae72f35cc5f64bbc756158374d26bf08ca5a357ab5...,7956c52f6a2cb2a5fcb461a8d752074bfadc811ef4efe7...,AIS_AND_RADAR,2000,400,2025-08-23T15:45:38+00:00,1850,NaN,1900.0,400.0,NaN,130.0,4.922014,52.377595,13014290783095305671,2025-08-23T15:45:40.075398Z,False,NaN,DE TIJD ZAL T LEREN,1745
12506230,186242,3900,600,125628.0,487474.0,140,39,-135,163.9,NaN,NAAR DE KLANT,False,13659,NaN,0a6987a732206d70d4f0370d2d9d8106f42f08e1da7352...,e670fdd90d9658af7936ddf8a41489b4cdd6e1d44f84d2...,AIS_AND_RADAR,3900,600,2025-08-24T07:41:15+00:00,8490,NaN,3400.0,500.0,NaN,297.0,4.955882,52.374353,178533967461504778,2025-08-24T07:41:16.217553Z,False,NaN,ZWAANTJE 6,941
12507067,186242,3900,600,125635.0,487474.0,10,10,2,75.6,NaN,NAAR DE KLANT,False,13659,NaN,0a6987a732206d70d4f0370d2d9d8106f42f08e1da7352...,e670fdd90d9658af7936ddf8a41489b4cdd6e1d44f84d2...,UNDEFINED,3900,600,2025-08-24T07:41:45+00:00,8490,NaN,3400.0,500.0,NaN,272.0,4.955985,52.374354,178533967461504778,2025-08-24T07:41:49.888000Z,False,NaN,ZWAANTJE 6,941
12514823,186242,3900,600,125635.0,487474.0,10,10,2,75.6,NaN,NAAR DE KLANT,False,13659,NaN,0a6987a732206d70d4f0370d2d9d8106f42f08e1da7352...,e670fdd90d9658af7936ddf8a41489b4cdd6e1d44f84d2...,UNDEFINED,3900,600,2025-08-24T07:41:45+00:00,8490,NaN,3400.0,500.0,NaN,272.0,4.955985,52.374354,178533967461504778,2025-08-24T07:41:49.888000Z,True,2025-08-24T07:41:49.887932Z,ZWAANTJE 6,941

In column "type" the values change so the "track-number" is not a unique identifier of each ship.

In [24]:
SAIL_destination["mmsi-number"].unique()

<ArrowStringArray>
['684ab637e543bedde8257a98157be7302cfee9c063b42ac80dbd4fb3e4453dca',
 '01fa8c2dae86d17a6628054f8cb2d36fdee874a83e549272cd444cbfe4bbff9b',
 '1a0442a1a66a9abbbb41b4f67153478b72cf63fabf1627e70c28aaaedc182572']
Length: 3, dtype: str

It seems that our filter of "SAIL" as destination seems to be too specific. Only 3 ships seem to have that destination.

We will try to look at all destinations that contain the word SAIL.

In [25]:
SAIL_destination = vessels[vessels["destination"].str.contains("SAIL", case=False, na=False)]

In [26]:
SAIL_destination["destination"].unique()

<ArrowStringArray>
[  'SAIL AMSTERDAM',         'SAIL AMS',   'SAIL AMSTERDAN',
          'SAILING',             'SAIL',    'SAIL ASTERDAM',
     'AMST SAIL IN', 'SAIL HOSPITALITY',         'SAIL2025',
     'SAILTRAINING',       'SAIL-NLAMS', 'IJMUIDEN PRESAIL',
   'SAIL_AMSTERDAM']
Length: 13, dtype: str

As it can be seen, there are much more SAIL destinations than just "SAIL"

In [27]:
vessels[vessels["destination"].isin(SAIL_destination["destination"].unique())]

,identifier-sensor,radar-length-cm,radar-beam-cm,position-x,position-y,speed-in-centimeters-per-second,x-speed,y-speed,orientation,significant-orientation,destination,pilot-on-board,track-number,imo-number,mmsi-number,eni-number,sensor-type,ais-length-cm,ais-beam-cm,update-time,type,sub-category,length,beam,port-role,short-term-avg-speed-in-cm-per-sec,lon,lat,id,upload-timestamp,oud_bericht,stale_since,name,hourminute
20,7946,2500,600,112644.0,493619.0,280,-272,66,283.7,NaN,SAIL AMSTERDAM,False,6145,NaN,0f450b7ee6f8d1506f14bda94061f1ce43f485884d3411...,cf46d22c1d3df8fad80671f811aa68a12fc9b699813b9d...,AIS_AND_RADAR,2500,600,2025-08-20T06:33:43+00:00,1850,NaN,2400.0,500.0,NaN,275.0,4.764448,52.428731,9366752887780198691,2025-08-20T06:34:08.318414Z,False,NaN,NaN,834
32,761,2300,400,116520.0,492715.0,260,-250,72,286.0,NaN,SAIL AMS,False,5491,NaN,9d8d7e47772b46a7d98f039a2763b3770d8be50cc9e892...,3f898b97bc6ced62b667967f3736f84f0dfa284a6cca0d...,AIS,2300,400,2025-08-20T06:33:44+00:00,8440,NaN,2400.0,400.0,NaN,276.0,4.821537,52.420892,6918341105560181984,2025-08-20T06:34:08.406774Z,False,NaN,NaN,834
105,33,3600,600,106758.0,496540.0,240,-180,158,311.3,NaN,SAIL AMSTERDAM,False,14002,NaN,d8892b9ba84f4fb91153592d16ff0444b759b8bfcaf86f...,eeb081ccf65ae548d9c6cb478ec033e3e2b9bf7bab5f9d...,AIS_AND_RADAR,3600,600,2025-08-20T06:33:46+00:00,8440,NaN,3600.0,600.0,NaN,241.0,4.677492,52.454495,8823795482923797041,2025-08-20T06:34:08.911453Z,False,NaN,NaN,834
115,496,3000,400,111467.0,493796.0,340,-330,82,283.9,NaN,SAIL AMSTERDAN,False,9972,a9afff4de82a655aa1de7d6b408261c162667be11ab10f...,6e16d62f241061f2fdceeb61b87557dd8eb4c016ba6bb2...,NaN,AIS_AND_RADAR,4800,600,2025-08-20T06:33:46+00:00,YACHT,Yacht,4100.0,600.0,NaN,339.0,4.747120,52.430229,4912576766204262171,2025-08-20T06:34:08.975411Z,False,NaN,NaN,834
180,1036,5800,1100,100233.0,497532.0,70,-70,-2,268.6,NaN,SAIL AMSTERDAM,False,7586,7b2c3f80fc580bd7c614331b7f7a72bade830eb67ea4b5...,36a43d7f0938c3534147660c133cf7af79ed23b642c201...,NaN,AIS_AND_RADAR,5900,1100,2025-08-20T06:33:49+00:00,YACHT,Yacht,5700.0,1100.0,NaN,126.0,4.581345,52.462796,14732753811615583123,2025-08-20T06:34:09.483653Z,False,NaN,NaN,834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12641492,127694,5100,700,116121.0,491296.0,0,0,0,0.2,0.2,SAIL AMSTERDAM,False,7498,NaN,609087ada29de6ab331556bb05c13d91f0c0534b17eda0...,1ef1243d327e7bd2288a6636a14580c83a11d8adda8e28...,AIS,5100,700,2025-08-24T08:59:37+00:00,8440,NaN,4500.0,600.0,NaN,0.0,4.815837,52.408111,7999538034719608023,2025-08-24T08:59:38.845795Z,False,NaN,ADMIRAAL VAN KINSBERGEN,1059
12641689,182996,1400,200,124849.0,487998.0,100,99,-13,97.5,NaN,SAIL,False,5682,NaN,684ab637e543bedde8257a98157be7302cfee9c063b42a...,659b552210cb5bdd2b81dc396fc2651173f996d4940fde...,AIS_AND_RADAR,0,0,2025-08-24T08:59:44+00:00,1850,NaN,2400.0,500.0,NaN,58.0,4.944396,52.379020,5627371271639895286,2025-08-24T08:59:46.332890Z,False,NaN,SPES,1059
12641756,126666,2600,400,118194.0,492636.0,0,0,0,0.2,NaN,SAIL,False,11417,NaN,1a0442a1a66a9abbbb41b4f67153478b72cf63fabf1627...,840f9cd012e6a20bb526548dd0aa4a8a7be3a134131fe9...,AIS,2600,400,2025-08-24T08:59:46+00:00,1850,NaN,2600.0,400.0,NaN,0.0,4.846153,52.420297,18355331754560669296,2025-08-24T08:59:48.327176Z,False,NaN,OVING 1,1059
12641761,158112,3600,600,112920.0,492111.0,0,0,0,0.2,0.2,SAIL AMSTERDAM,False,6534,NaN,d8892b9ba84f4fb91153592d16ff0444b759b8bfcaf86f...,eeb081ccf65ae548d9c6cb478ec033e3e2b9bf7bab5f9d...,AIS,3600,600,2025-08-24T08:59:46+00:00,8440,NaN,3600.0,600.0,NaN,0.0,4.768695,52.415200,8823795482923797041,2025-08-24T08:59:48.348905Z,False,NaN,NIL DESPERANDUM,1059
12641972,185648,3300,400,123711.0,487685.0,0,0,0,0.3,NaN,SAILTRAINING,False,13575,e6567f4cf465561d47498a1823e678d56d7baec7dfb3bb...,23b6140652f8f359db77531d4645b166b2d5978314f8fa...,NaN,AIS,3300,400,2025-08-24T08:59:53+00:00,YACHT,Sail Training Ship,4000.0,600.0,NaN,0.0,4.927712,52.376144,2464178224249038514,2025-08-24T08:59:55.823713Z,False,NaN,EYE OF THE WIND,1059

In [28]:
vessels[vessels["destination"].isin(SAIL_destination["destination"].unique())]['mmsi-number'].unique()

<ArrowStringArray>
['0f450b7ee6f8d1506f14bda94061f1ce43f485884d3411289596755d85b9eff9',
 '9d8d7e47772b46a7d98f039a2763b3770d8be50cc9e892573b6185ee62c5512d',
 'd8892b9ba84f4fb91153592d16ff0444b759b8bfcaf86f248f21884c7696e9ea',
 '6e16d62f241061f2fdceeb61b87557dd8eb4c016ba6bb2da7892fc88d5443398',
 '36a43d7f0938c3534147660c133cf7af79ed23b642c2011aec58205b4b5acf11',
 '85432077f24a88302d8e4d993d93c0cc7a24c438e2f808c1efe94ac826e666dd',
 'e3e368c268630836312120347edb5b93a94a3eea95244c5099fd6e179dbdb350',
 '684ab637e543bedde8257a98157be7302cfee9c063b42ac80dbd4fb3e4453dca',
 '01fa8c2dae86d17a6628054f8cb2d36fdee874a83e549272cd444cbfe4bbff9b',
 '609087ada29de6ab331556bb05c13d91f0c0534b17eda0fa41fe76e25679f278',
 '07c4ce70e68fe2035bc4a2f458b4ff0e18e72e730a2a59ba770b1f6930566d10',
 'aa382cfdb2e8c44af9c3e14e278eeb303a5301f1b032f976c98559fd2494ed09',
 'e08e239ebcb7c94eed7ff75c7f51456f2b873b5dd001793792c0f2e11e098946',
 'aa922a76c1f83358ab16393de852cfc2508b17f5ba5ad284131b8c36321dcc65',
 '07a5eb9f93ed5f6e7b9023fd3cf1a80eecc85a367643440dafc6175745ea242f',
 '23b6140652f8f359db77531d4645b166b2d5978314f8fa1b4c9572e84e59bc7b',
 '9150aa8a6502e91effba69a1f27baa4823e954396e03da9d7f0b2ea8f1e7031e',
 '75869925c7f34300cc7117f6d840b1f71a141843b478c2c5666dd9ae70c60da0',
 '29978dc13cbeae8f96f304350c9264d8e777515f3b0f7050c5f327e4fb5d9743',
 '1a0442a1a66a9abbbb41b4f67153478b72cf63fabf1627e70c28aaaedc182572',
 '4dcc0c24d8e34c951faa476d9151bf62b138904ba271ef89ca17a5764601d7fd',
 'bdffc48ad0d36a7ddf9e7ad5091e37754d79b97d080ed9dbf89ca8c7a1b65938']
Length: 22, dtype: str

Still only 22 boats. Lets check if actually all boats from the original dataframe are from SAIL.

In [29]:
vessels['mmsi-number'].unique()

<ArrowStringArray>
['4e73147932245214a49503c66d37ccb8e04dc06299fbf59ab6e1a1d2a2cc4b91',
 'dfb315a6b5cff224394af277e0053d057db332a988ccc3aa1ee71c8475e1d853',
 '0d11ea82dff9438409d2a9f3416802933496c659a0fa84ae810a958b0c06c492',
 'e324f61d2312f715bfa3a70729570922528bcb0172e58cae028ad0adb975b06d',
 '57f837f1599be8a65248899206da5a2d4171799b3fd5ba7e17d8d8e1635fe6b1',
 'a53fd259fd7844b3faf20a5791a88999f11b624bf03d0e8a23d03b7ab11df8ce',
 'b4bb42fd9218b78f03dc6fc74439cb6324b107129f2c917654d38232c79f49bc',
 'e649e3b94d870481edf821808643a8f7386c414f2e1246bec8fbc7199a4049ef',
 'f3a5685ae40c4780754c3d258381475d62d93549f86d4cf2d4c14422d4643bf3',
 'ef14ca7f9340ed216f1d3aa2926717b8262480711947bb94123978e4963b22d7',
 ...
 '840e60f2c1a578b1d70671a02cba2a82f66ae6a51eff2e0d86cb4c530511079c',
 '433160318542c826a9f971207e1026dad401ddf02344ccf3d16ce7b976e297b2',
 '71123cf42ae304b0b63528230f97444e85fd91cb7e5cd151511484d46e5a94d9',
 'be707504c27104a5a37b84a91aa85810349cdbf2d51f96611b1f41e95de7fce5',
 '748eb55be5525b3dd23a9bcebcbf62ad9621bafc9c819258b9acc20cbc0ad543',
 '3ab82d4b4b08e06ef538650beeae1935f9fc9fb72e8488adfebd60cf88ba7099',
 'b9def7cd3fecb9c06bd882ae54d5fa2455a8b149221911003db350bb9e1d6d77',
 'b334d60223caff29ee55f7b221d8530be4c066aedd58a27618a8eb8dfe711e0b',
 '182adf1020bcd47af511152c7373699ce29ec339c578699906c4530c65b3535e',
 '6d45a5a0d59a5b99e33a5a9721276d18a16437e8301539677b17419097f3284d']
Length: 3015, dtype: str

The original dataframe seems to have too many boats. In SAIL 2025 around 1000 boats participated. Lets check unique sub-categories.

In [30]:
vessels["sub-category"].unique()

<ArrowStringArray>
[                                        'Tug',
                          'Sail Training Ship',
                                           nan,
                               'Patrol Vessel',
                                 'Buoy Tender',
                    'Chemical/Products Tanker',
                            'Vehicles Carrier',
             'Passenger/Ro-Ro Ship (Vehicles)',
                          'General Cargo Ship',
                                'Bulk Carrier',
                                  'LPG Tanker',
             'Container Ship (Fully Cellular)',
                          'Crew/Supply Vessel',
                                'Pilot Vessel',
                                   'Crew Boat',
                    'Service Operation Vessel',
                              'Sailing Vessel',
                                       'Yacht',
                              'Fishing Vessel',
                            'Passenger/Cruise',
                              'Shuttle Tanker',
                              'Utility Vessel',
                      'Research Survey Vessel',
                              'Passenger Ship',
                      'Asphalt/Bitumen Tanker',
                            'Ro-Ro Cargo Ship',
                            'Crude Oil Tanker',
                             'Products Tanker',
                          'Work/Repair Vessel',
                                'Crane Vessel',
                       'Standby Safety Vessel',
             'Trailing Suction Hopper Dredger',
                           'Exhibition Vessel',
                                'Salvage Ship',
                               'Supply Tender',
                          'Museum, Stationary',
                      'Search & Rescue Vessel',
                       'Diving Support Vessel',
                   'Support Platform, jack up',
                          'Heavy Load Carrier',
            'Combination Gas Tanker (LNG/LPG)',
                       'Drilling Rig, jack up',
                        'Platform Supply Ship',
                     'Offshore Support Vessel',
 'Wind Turbine Installation Platform, jack up',
                             'Yacht (Sailing)',
                     'Water Injection Dredger',
                       'Molten Sulphur Tanker',
                     'Fishery Research Vessel',
                      'Anchor Handling Vessel',
                    'Pollution Control Vessel',
              'Replenishment Dry Cargo Vessel',
                             'Suction Dredger',
                   'Crude/Oil Products Tanker',
        'Heavy Load Carrier, semi submersible',
                      'Bunkering Tanker (LNG)',
                                  'LNG Tanker',
      'Commissioning Service Operation Vessel',
                                     'Frigate',
                              'Cement Carrier',
                  'Anchor Handling Tug Supply',
                               'Hopper, Motor',
                              'Command Vessel',
                                  'Minehunter',
             'Yacht Carrier, semi submersible',
                    'Refrigerated Cargo Ship ',
                       'Open Hatch Cargo Ship',
              'Bulk Carrier, Self-discharging',
                     'Pipe Layer Crane Vessel',
                  'Container/Ro-Ro Cargo Ship',
                          'Aggregates Carrier',
                       'Palletised Cargo Ship',
                           'Edible Oil Tanker',
      'Maintenance Platform, semi Submersible',
                       'Fishery Patrol Vessel']
Length: 75, dtype: str

Create a .txt file to select possible candidates to reduce the amount of ships and make more managable the dataset.

In [31]:
destinations = sorted(
    vessels["sub-category"].dropna().unique()
)

with open("subcategories.txt", "w", encoding="utf-8") as f:
    for destination in destinations:
        f.write(str(destination) + "\n")

From this .txt we can see that there are many ship sub categories that aren't compatible with tha SAIL theme and are rather cargo ships or boats related to the port functionality. First we decided to keep the following:

["Exhibition Vessel", "Frigate", "Museum, Stationary", "Passenger Ship", "Passenger/Cruise", "Sail Training Ship", "Sailing Vessel", "Yacht", "Yacht (Sailing)"]

Other possible candidates:

["Command Vessel", "Minehunter"]

Also, we should consider nan.

In [32]:
mask_1 = ["Exhibition Vessel", "Frigate", "Museum, Stationary", "Passenger Ship", "Passenger/Cruise", 
          "Sail Training Ship", "Sailing Vessel", "Yacht", "Yacht (Sailing)"]


vessels[vessels["sub-category"].isin(mask_1)]["mmsi-number"].unique()

<ArrowStringArray>
['dfb315a6b5cff224394af277e0053d057db332a988ccc3aa1ee71c8475e1d853',
 'caaf2ee103c66c432478aee4ba8b2f542f5c8a5b030c8fb97a782b64495ed636',
 'e36f4961a219f8e40e691cd750cc76af0c167c8f9538851b4e7ec45961f5cd70',
 '7a14e3a377c5da6d886327a8e67afc40bc1cc2cc2519c5137454f6b98822cbc1',
 'e2b89940f87608e62f63b09387bb3302f16af810ec1a4d7354d2a5301c58ceca',
 '6e16d62f241061f2fdceeb61b87557dd8eb4c016ba6bb2da7892fc88d5443398',
 '90d64527388ab5e4305c27a6a6d1b6695de5bc1bd772cf66af1f3e06cea7440d',
 '36a43d7f0938c3534147660c133cf7af79ed23b642c2011aec58205b4b5acf11',
 'cbfab6a106e38d9b50b655e1616e822ebf58b10091aac5ac62f2bd36a56187d0',
 'aa435ec05309b11ea804887a171b4e15061be998b832d8cdc0c593940ea5448c',
 '8b4630d08af4a7a14c325e06aa18aef5632ef88dbd639c68480d1a043b25dbc8',
 '4f5df112ad4d7bcc762c51f97e5f8fd7d673a0e07351a296ac9be4e9deee34a5',
 'eba30a744379df6c5d183d42b79b85f59b87cfa86f9e1c47121457199ac9822b',
 '66acee3a209bb4e0439915a124ce96f6d49bb5ab55b3c95ff6bf2b98b709b828',
 '7bbb21dfb51fadfb76dbddda1572397d76a7d74331688c5c5dc3be5cf5bcfbf0',
 '9dd995d12cc1b167a94a1d39bdb41c1a5edc161676012697e6face7573c4f367',
 'ebcc5d46f37e8a5b9e2166da82bf102480df53a790b29d13777e61c1bdff610e',
 '7d0e2791d302aca22e1e1b4cbf577edcb64dbc5e58fd3cfe2e6a94eb14489813',
 '5830bf77e889d4ba3e90848ecdde497c075c5e0a51101aa420e0cedfc168dde9',
 '1f73fa18b35c591f69c22707e8a71a1ba25d255883a1cfc0cf7468781ed446cc',
 'd04c973bb740edf89364dfcf4f2291dfdcc01f63456e3fc755f25505ec4ae518',
 '6ca09975c9077ef5864fa32b4d1180b09eb8b9329364b40536c7f5bbb6b4fe76',
 'b11654e169e7d412f8dec02162011649a00d28742e5ac40e3bdf1831a842372d',
 '8781370107c1da8af805ea89465073cc07a1c4d83686116e0c2806250bab6517',
 '72a730609255f287e76c681d16301f610460ff33a4b1a20ed1458add16d4eb31',
 '5b34d2ae5402d4cb33984991ba87ee150bcd4c4708f2cdaeb075d1e239b24897',
 'f96ebfc158047684937529421e903641caa6760ecaf5140ec98fda747d6fc6be',
 '07c4ce70e68fe2035bc4a2f458b4ff0e18e72e730a2a59ba770b1f6930566d10',
 '459a3320c00eeba74c2dd2ae71277e2cdfef96a8f8cc3c61bbee7f4e6da99356',
 'f9d6cb85f0bbd9c0fce0149ea60173e67ef5e67409465fe317648916a63f29d6',
 'fba77a59729f17f87bebe416200b7e695d1cd07dd710c4fdcb5ef35264ab2b13',
 'c056322239165db922e004a4145868ac6da38d110c6c33443a533fe71a811238',
 'c1c70c186af2c28023a873a37e115a8386e959486f1c1c35437a4e2badfc5ce6',
 'e3f959873981c5cc537bd8f7f283d9c4b174dd9147a7170010cd888a923a0ed2',
 'c0f63736a665c9fa0757f819ce06d3d857f5f599f1efd7e6cf834da186bb18af',
 'a5357afe24a21b30117575dd8961bff2ca520029e73f123dbfc7d66c35b6fd8e',
 'bdffc48ad0d36a7ddf9e7ad5091e37754d79b97d080ed9dbf89ca8c7a1b65938',
 '011454c8e087967d50a74a1da8fc272cb2eff6310c783c3c803c2a69a5225658',
 '61f0da62796377f36a86a4c5219fcc82330f4b63e26bf863e0184fef61f99c81',
 '43ee6f364e22eb93023063c336d5264e7b059fcaf565a5b6fa8aa52be7ed2ba8',
 '99fb2e9894112e10e18eea8d9fd573f41a5c012b9de21102e1b2541b495a4dc3',
 '1f7153609b34c4941c0bee8ed5d92b80bd4e0f57145af4ba7d534b7d6d2e5b69',
 'e5f426ea51dd268d463e8267ffa0707a3b32e4ca2f09e3efbc29863b14b7b4ef',
 '1ea3c96e2857a699c6040b569ca4dc4363e98fc2bee482a81352bd1bdf6dcf06',
 '8765b77c9df584282ab74f5413b72e77e3a53b8f074baa748de0018773401baa',
 '048ce39bbefd25bbdbda4d687a5ba8024f3697c3c3940ff6bad4005b492a123d',
 '8b5bd01a403dc93f1aa8456be6715d89b453119ab7a887ede778047bf35f4d56',
 '70b19749118986ace898bc29c5613dbebb7465988a8cc95ba98c3a755b0d4b04',
 '23b6140652f8f359db77531d4645b166b2d5978314f8fa1b4c9572e84e59bc7b',
 'cda118071be736d95f0d49e078242fd2c84d7862a0759d945b3dd1e28008cf96',
 'd1650f72de871bece4a94050aab5edfc72e1d6ea200d6af24367bec75b7d92e4',
 '8ce3f17236f8afe6c0ffd4259d39e6b62a58dc49023a9249cb81eecc1b620e8e',
 '62550156be03a988787b18bcefe176383d7bb6789db61443b294925066696124',
 '6c08b57ef2d9dc3056bf6e830fef30ddb0cfad05e4e9f91a03bed1a1755f3829',
 '61e2128148c5b9df77909c0d86d1dd887d641313a9c591170db0f7f541a6e73f',
 'ee12654e1f1cf98042bef64c8cc884ad5f42dcba030e723d07858c1b77aefdb8',
 'f6ee70171bc44de0998333346981392531081b00925511c658b4e8cf6e0fd34d',
 'b5da6b98166f4867e669cf65938f10cd4e9a3c4e8593f653959584861cf1f214',
 '44ba54b87f8b0ee5b0c457c44d2ffdf218ad03b9e466a7f15700eaa782feac3d',
 '1b12058395ff523ab095865216650e3f52ac262f51fa8f1b8606d7ded8766693',
 'ac5f6dc5cf7a93e44e3e327289a7021c5898a7719fdd931577bd4845cb1fbaba',
 '8664374766d4129764483e5dd83e2134ee38965c24b93ce328d4adbc66e89549',
 '3fc38f434fc273910d81f4fc212792dcd690efdf9866b2945f08cf447a51ddd1',
 '20d4de253509fa3c6147e30b9f2949d92d18aa2da84f679f5d8d5825f0f979f4',
 '43ab4a593627f233c8bd8de9d35a2fe733797ca0d8c758f8d93496b89bb6ab7d',
 '8a97cb211bf1be89efcd9a0f92177374cf52bf56b4063c94faab6dd9f809b737',
 'c7b382fdd385384a938ee40c321f7756b222d8b8182f3e94055eacfaa574151f',
 '20704793f5d0773ee12e9ec4f50d866581e99168c3cbe2b8a61eeb39a3a65954',
 '0c3de68b72cd1f5c790a5d8ea77c964008c5f3075b305953f7912835846f3ce6',
 'd10ff18f7363df599c0c25a0913d39570dc2a77d651faf52cadc2f659dac452a',
 'f8a042e6d0f69b68518330e037a4633278629abac5483c47d13e2127b9eb1995',
 '7251f227d3979e4de1eda0c8e42cc353dd8e6c6c4d86dfedf7bafd8c5c9bfc24',
 'c3a9182973b886c6a15697256b71235f0b668cbb8e9849e0e0aa8f0271186881',
 'f1edd0f24ac9076c8440a2b04755007b86e9bbd8c153c21a7e0778598418a4c4',
 '48292e4a6730f9fe73d0d3e31bc3c03f2889998e139f10ac49940a87f32fd907',
 'dea2e7a66cd78b1a4d698f212b66c560b5ed413156558c0c1fdd3404d7516628',
 '102a0301d7898433308dc98e3a0ad3f04563d5e6f5704151805597c235178d9f',
 '3ad0de4a3d03dae7ef387a85cf9a529aa99a0b3cb48ba9ac2eea75f3b57fb948',
 '673f8537a157fbcd85946e86ab64c1d340f44471ff74429e046f190e0d41fdcc',
 'c1cf377a31ad49e57fcd18193de70ba79bab38b47ecbb459dad5e646b83f221f',
 '182adf1020bcd47af511152c7373699ce29ec339c578699906c4530c65b3535e']
Length: 81, dtype: str

These 81 ships we are keeping because their category fits the sail theme. Lets check nan values in sub-category column filtering by destination.

In [33]:
vessels[
    (vessels["sub-category"].isna()) &
    (vessels["destination"].isin(SAIL_destination["destination"].unique()))
]["mmsi-number"].unique()

<ArrowStringArray>
['0f450b7ee6f8d1506f14bda94061f1ce43f485884d3411289596755d85b9eff9',
 '9d8d7e47772b46a7d98f039a2763b3770d8be50cc9e892573b6185ee62c5512d',
 'd8892b9ba84f4fb91153592d16ff0444b759b8bfcaf86f248f21884c7696e9ea',
 'e3e368c268630836312120347edb5b93a94a3eea95244c5099fd6e179dbdb350',
 '684ab637e543bedde8257a98157be7302cfee9c063b42ac80dbd4fb3e4453dca',
 '01fa8c2dae86d17a6628054f8cb2d36fdee874a83e549272cd444cbfe4bbff9b',
 '609087ada29de6ab331556bb05c13d91f0c0534b17eda0fa41fe76e25679f278',
 'aa382cfdb2e8c44af9c3e14e278eeb303a5301f1b032f976c98559fd2494ed09',
 'e08e239ebcb7c94eed7ff75c7f51456f2b873b5dd001793792c0f2e11e098946',
 'aa922a76c1f83358ab16393de852cfc2508b17f5ba5ad284131b8c36321dcc65',
 '07a5eb9f93ed5f6e7b9023fd3cf1a80eecc85a367643440dafc6175745ea242f',
 '9150aa8a6502e91effba69a1f27baa4823e954396e03da9d7f0b2ea8f1e7031e',
 '29978dc13cbeae8f96f304350c9264d8e777515f3b0f7050c5f327e4fb5d9743',
 '1a0442a1a66a9abbbb41b4f67153478b72cf63fabf1627e70c28aaaedc182572',
 '4dcc0c24d8e34c951faa476d9151bf62b138904ba271ef89ca17a5764601d7fd']
Length: 15, dtype: str

Here we get other 15 boats with destination "SAIL" that had no sub category. No we can define a new dataset that keeps only these boats.

In [34]:
df_1 = vessels[vessels["sub-category"].isin(mask_1)]
df_2 = vessels[(vessels["sub-category"].isna()) & (vessels["destination"].isin(SAIL_destination["destination"].unique()))]

SAIL_ships = pd.concat([df_1, df_2])

In [35]:
sorted(SAIL_ships['name'].dropna().unique())

['ADMIRAAL VAN KINSBERGEN',
 'AIDAPERLA',
 'ALBATROS',
 'ALEXANDER VON HUMBOLDT II',
 'ANNA AF SAND',
 'ANTIGUA',
 'ANTONIUS',
 'AQUILA',
 'ARCTIC SUNRISE',
 'ARTEMIS',
 'ATLANTIS',
 'AVONTUUR',
 'BELEM',
 'BOUDRAGON',
 'CAPITAN MIRANDA',
 'CARAVEL VERA CRUZ',
 'CASTOR',
 'CELEBRITY APEX',
 'CHRISTIAN RADICH',
 'CORSARO II',
 'DAR MLODZIEZY',
 'DAR SZCZECINA',
 'ECOLUTION',
 'EENDRACHT',
 'EIVISSA',
 'ENGELINA',
 'EUROPA',
 'EVERTSEN',
 'EYE OF THE WIND',
 'FRUITION',
 'GALEON ANDALUCIA',
 'GIPSY MOTH',
 'GORCH FOCK',
 'GRACE KELLY',
 'GULDEN LEEUW',
 'HEBRIDEAN SKY',
 'HENDRIK KARSSEN',
 'HENDRIKA BARTELDS',
 'HOOP OP WELVAART',
 'HYDROGRAAF',
 'IDE MIN',
 'IRIS',
 'J. R. TOLKIEN',
 'JANTJE',
 'JAVAZEE',
 'JOANNA SATURNA',
 'JOHANNA',
 'KAMPER KOGGE',
 'KLEINE JAGER',
 'KONINGIN EMMA',
 'LA BELLE POULE',
 'LADY CHRISTINE',
 'LE FRANCAIS',
 'LEGEND',
 'LOTH LORIEN',
 'LUTGERDINA',
 'MARION',
 'MERCUUR',
 'MILPAT',
 'MINERVA',
 'MORGENSTER',
 'MUTIN',
 'NAO VICTORIA',
 'NEHALLENNIA',
 'NIEUW STATENDAM',
 'NIL DESPERANDUM',
 'NORWEGIAN PRIMA',
 'NORWEGIAN SKY',
 'OCEAN MAJESTY',
 'OOSTERSCHELDE',
 'OVING 1',
 'PARAAT',
 'PASCUAL FLORES',
 'PI',
 'REGINA MARIS',
 'RUPEL',
 'SAGRES',
 'SCARLET LADY',
 'SEAWOLF',
 'SHABAB OMAN II',
 'SPES',
 'STAD AMSTERDAM',
 'SUZANNA',
 'SWAENSBORGH',
 'THALASSA',
 'TOEKOMST',
 'TRES HOMBRES',
 'TRIP JUNIOR',
 'TWISTER',
 'UNION',
 'URANIA',
 'VALOR',
 'WILL',
 'WILLEM',
 'WITNESS',
 'WYLDE SWAN']

Crossing the unique names we got with the official sail page we got most of the mail vessels present at SAIL. This number is much more managable than 3000 ships with their position every 1 minute.

# TomTom data & NWB

This two data files contain information on street coordinates and their traffic flow. Let's analyze their contents.

In [36]:
tomtom.head(10)

,time,data
0,2025-08-20T08:36:29.749039+02:00,"id,traffic_level\n210398154,0.69\n209398060,0...."
1,2025-08-20T08:37:13.722331+02:00,"id,traffic_level\n213399051,0.49\n210397047,0...."
2,2025-08-20T08:37:57.858546+02:00,"id,traffic_level\n213398008,0.49\n213398007,0...."
3,2025-08-20T08:38:41.968526+02:00,"id,traffic_level\n213398007,0.5\n213398008,0.4..."
4,2025-08-20T08:39:26.191558+02:00,"id,traffic_level\n213398007,0.48\n209398043,0...."
5,2025-08-20T08:40:10.379436+02:00,"id,traffic_level\n209398060,0.56\n210398154,0...."
6,2025-08-20T08:40:54.631955+02:00,"id,traffic_level\n213398007,0.48\n213398008,0...."
7,2025-08-20T08:41:38.951747+02:00,"id,traffic_level\n213398007,0.46\n209398043,0...."
8,2025-08-20T08:42:23.216726+02:00,"id,traffic_level\n213398007,0.62\n209398043,0...."
9,2025-08-20T08:43:07.538616+02:00,"id,traffic_level\n213398007,0.63\n210397107,0...."

In [37]:
tomtom.iloc[0, 1]

'id,traffic_level\n210398154,0.69\n209398060,0.68\n214397017,0.69\n210396019,0.76\n209398051,0.75\n211399063,0.78\n213400118,0.88\n214390018,0.0\n221385011,0.21\n205395003,0.53\n209394068,0.45\n223389002,0.7\n209396080,0.52\n210396026,0.62\n206394103,0.61\n210392046,0.64\n203394110,0.71\n209396061,0.77\n209396064,0.77\n210395002,0.79\n210395003,0.79\n222382010,0.74\n204395002,0.79\n209393004,0.77\n210393011,0.77\n213388004,0.81\n208394010,0.84\n204395010,0.86\n236379061,0.4\n236380042,0.0\n236381037,0.25\n237381031,0.0\n240386020,0.0\n240374009,0.0\n242374224,0.0\n236374104,0.44\n242376103,0.52\n235378097,0.53\n241377202,0.52\n237375065,0.66\n227387024,0.56\n239374034,0.77\n242378035,0.71\n238375060,0.64\n241385078,0.64\n240374124,0.71\n236377051,0.7\n235374030,0.7\n235377028,0.71\n238374078,0.72\n240378022,0.72\n240378024,0.72\n240378051,0.72\n239375112,0.74\n237378041,0.77\n226396008,0.78\n226395024,0.78\n242375111,0.83\n233385033,0.87\n241383038,0.89\n241383074,0.89\n242383081,0.89\n237376105,0.93\n236376132,0.94\n236376068,0.95\n240385044,0.96\n235368057,0.61\n240372095,0.57\n241371043,0.55\n235371067,0.56\n235371115,0.56\n238371072,0.56\n238371078,0.56\n237368040,0.59\n235367021,0.8\n238368090,0.62\n240372130,0.59\n241370041,0.7\n236369050,0.68\n236371026,0.68\n236371032,0.68\n237368041,0.68\n237369018,0.68\n239368033,0.72\n243369065,0.71\n241369075,0.73\n242369067,0.73\n240369086,0.74\n242367140,0.77\n243370043,0.83\n236369030,0.79\n238368123,0.79\n239368010,0.79\n239370071,0.79\n237369063,0.79\n237369075,0.79\n242368011,0.79\n242368062,0.79\n240372109,0.79\n242368095,0.79\n242369050,0.79\n234369067,0.88\n235369066,0.81\n236369074,0.81\n239369045,0.8\n241368022,0.9\n243370006,0.83\n240369049,0.91\n235370051,0.96\n241368027,0.96\n235371058,0.95\n235371116,0.95\n235371142,0.95\n235372060,0.95\n235372103,0.95\n241374082,0.0\n241374085,0.44\n240375037,0.58\n240375104,0.6\n241375085,0.66\n207394027,1.0\n210392041,1.0\n210396022,1.0\n210397093,1.0\n210397096,1.0\n214385001,1.0\n214400063,1.0\n214400067,1.0\n215384028,1.0\n215400046,1.0\n215400048,1.0\n224394004,1.0\n234374057,1.0\n235369054,1.0\n235370042,1.0\n235370049,1.0\n235375092,1.0\n235375094,1.0\n235376013,1.0\n235376033,1.0\n235377018,1.0\n236368049,1.0\n236368051,1.0\n236368055,1.0\n236372023,1.0\n236376018,1.0\n236378082,1.0\n237369037,1.0\n237376084,1.0\n237378050,1.0\n237379027,1.0\n237380003,1.0\n237381034,1.0\n237381035,1.0\n237382018,1.0\n238369037,1.0\n238369039,1.0\n238369058,1.0\n238374012,1.0\n238375081,1.0\n238375083,1.0\n239366111,1.0\n239369096,1.0\n239374061,1.0\n239374063,1.0\n239377045,1.0\n240367044,1.0\n240369058,1.0\n240370019,1.0\n240370079,1.0\n240371010,1.0\n240371097,1.0\n240371099,1.0\n240372022,1.0\n240373011,1.0\n240373033,1.0\n240374053,1.0\n240374054,1.0\n240376021,1.0\n240376052,1.0\n240377002,1.0\n240377016,1.0\n240377039,1.0\n240377089,1.0\n241369066,1.0\n241369085,1.0\n241370109,1.0\n241371059,1.0\n241372031,1.0\n241373033,1.0\n241373042,1.0\n241373050,1.0\n241373069,1.0\n241373089,1.0\n241373095,1.0\n241373100,1.0\n241374079,1.0\n241374111,1.0\n241375016,1.0\n241375019,1.0\n241376017,1.0\n241376023,1.0\n241376060,1.0\n241376138,1.0\n241377024,1.0\n241382072,1.0\n241383057,1.0\n242367085,1.0\n242369027,1.0\n242369080,1.0\n242369098,1.0\n242370045,1.0\n242372047,1.0\n242372061,1.0\n242373050,1.0\n242373060,1.0\n242373169,1.0\n242373187,1.0\n242373188,1.0\n242374007,1.0\n242374138,1.0\n242374171,1.0\n242374197,1.0\n242374271,1.0\n242375035,1.0\n242375063,1.0\n242375096,1.0\n242386021,1.0\n243368002,1.0\n243368021,1.0\n243370052,1.0\n243371019,1.0\n243371104,1.0\n243372001,1.0\n243372023,1.0\n243372048,1.0\n243373005,1.0\n243373035,1.0\n241375082,0.89\n241375089,0.89\n242375039,0.89\n242376009,0.89\n242376138,0.89\n241374006,0.0\n243372044,0.0\n242370105,0.23\n241371050,0.54\n241373007,0.72\n242373035,0.68\n240371050,0.6\n240371075,0.6\n243371009,0.65\n243372031,0.63\n243371088,0.7\n240370084,0.73\n242369061,0.79\n240373076,0.83\n243371057,0.89\n240369044,0.91\n600114832,0.71\n600280559,0.0\n600112951,0.61\n600280379,0.6\n600112960,0.71\n600123731,0.37\n600124907,0.0\n243376052,0.0\n243376061,0.0\n600287501,0.0\n600123864,0.32\n600362834,0.0\n246376019,0.4\n245375026,0.46\n600124800,0.41\n600122547,0.57\n600226032,0.31\n245378132,0.32\n245373029,0.6\n243376070,0.33\n600122553,0.5\n600122556,0.5\n243375134,0.5\n600122692,0.73\n600123941,0.6\n244375048,0.58\n600124878,0.62\n600124997,0.56\n600225775,0.6\n600124973,0.61\n600122526,0.68\n248381082,0.63\n248381083,0.71\n246378114,0.65\n245375016,0.64\n600122528,0.78\n245374057,0.74\n244375137,0.76\n247373018,0.77\n247373078,0.77\n246373027,0.78\n246373086,0.78\n245374097,0.78\n244373050,0.79\n244373209,0.79\n600254072,0.86\n245373027,0.87\n244375136,0.63\n248373112,0.9\n244380057,0.91\n600362504,0.81\n600122949,0.5\n600124951,0.44\n600122515,0.53\n245371119,0.66\n600124759,0.66\n600234375,0.75\n247366094,0.64\n600124676,0.74\n600123884,0.7\n600122539,0.68\n246369124,0.69\n244370050,0.73\n245371027,0.7\n247371105,0.77\n247370075,0.78\n247370091,0.78\n247366078,0.77\n600124225,0.78\n244370036,0.77\n600124462,0.77\n600122513,0.78\n244371108,0.73\n600123979,0.76\n600124675,0.79\n244371122,0.79\n247368066,0.86\n248368065,0.86\n600122591,0.88\n600234615,0.92\n246370059,0.94\n246370060,0.94\n243373141,1.0\n243374040,1.0\n243374048,1.0\n243374086,1.0\n243374143,1.0\n243374172,1.0\n243374204,1.0\n243374244,1.0\n243374259,1.0\n243374286,1.0\n243379017,1.0\n243381033,1.0\n243382025,1.0\n243382055,1.0\n243383025,1.0\n243383026,1.0\n243383032,1.0\n243383034,1.0\n243383037,1.0\n243383105,1.0\n244365041,1.0\n244369061,1.0\n244372023,1.0\n244372091,1.0\n244374060,1.0\n244377049,1.0\n244377072,1.0\n244377074,1.0\n244377110,1.0\n244377115,1.0\n244378114,1.0\n244378129,1.0\n244378158,1.0\n244378160,1.0\n244379010,1.0\n244379026,1.0\n244379033,1.0\n244381035,1.0\n244381061,1.0\n244384001,1.0\n244385032,1.0\n245365028,1.0\n245370130,1.0\n245370131,1.0\n245371075,1.0\n245372093,1.0\n245372112,1.0\n245377009,1.0\n245377107,1.0\n245378060,1.0\n245378069,1.0\n245379012,1.0\n245379095,1.0\n245380046,1.0\n245381157,1.0\n245382101,1.0\n245383022,1.0\n245384024,1.0\n245384025,1.0\n246366047,1.0\n246370067,1.0\n246372124,1.0\n246377141,1.0\n246382068,1.0\n247377003,1.0\n247377056,1.0\n247378046,1.0\n247378047,1.0\n247379112,1.0\n247380037,1.0\n247380070,1.0\n248366062,1.0\n248379063,1.0\n248380001,1.0\n248380103,1.0\n248380115,1.0\n248380121,1.0\n248380135,1.0\n248380138,1.0\n248381011,1.0\n249366051,1.0\n249366078,1.0\n249373060,1.0\n249378106,1.0\n249378112,1.0\n249378150,1.0\n249379013,1.0\n249379116,1.0\n249379132,1.0\n249380049,1.0\n250367136,1.0\n250367138,1.0\n250373007,1.0\n250373012,1.0\n250377001,1.0\n250377008,1.0\n250378014,1.0\n250378032,1.0\n250378040,1.0\n250378058,1.0\n250378084,1.0\n251370010,1.0\n251371005,1.0\n251378151,1.0\n251378159,1.0\n251378160,1.0\n251378161,1.0\n251379002,1.0\n252378058,1.0\n600119765,1.0\n600121718,1.0\n600121924,1.0\n600122126,1.0\n600122570,1.0\n600122864,1.0\n600123203,1.0\n600123444,1.0\n600123744,1.0\n600123958,1.0\n600123960,1.0\n600123980,1.0\n600124034,1.0\n600124247,1.0\n600124449,1.0\n600124698,1.0\n600124746,1.0\n600124752,1.0\n600124760,1.0\n600124847,1.0\n600156603,1.0\n600200456,1.0\n600200457,1.0\n600224712,1.0\n600224732,1.0\n600280380,1.0\n600280405,1.0\n600287311,1.0\n600288267,1.0\n600288276,1.0\n600362707,1.0\n600362854,1.0\n600362896,1.0\n600362907,1.0\n600362931,1.0\n600362933,1.0\n600362947,1.0\n253372001,0.47\n250380026,0.76\n250379102,0.93\n252378077,0.95\n250378127,0.97\n600362941,0.0\n600362837,0.59\n600362832,0.62\n243381087,0.61\n244375100,0.79\n600124404,0.52\n246371058,0.58\n600362914,0.72\n600362915,0.68\n600362918,0.68\n600362937,0.72\n600124213,0.73\n243373150,0.79\n600124244,0.79\n245373014,0.87\n600125467,0.18\n250367130,0.31\n600125468,0.44\n250367109,0.58\n249372106,0.66\n249372100,0.8\n600447070,0.62\n600497855,0.71\n600538430,0.88\n600380101,0.24\n600380172,0.54\n600519287,0.54\n600496656,0.58\n600514202,0.61\n600474859,0.62\n600470470,0.79\n600408410,0.5\n600408267,0.66\n600408388,0.52\n600496921,0.59\n600405344,0.63\n600403509,0.56\n600388227,0.68\n600478393,0.61\n600403673,0.67\n600423630,0.72\n600408556,0.63\n600405425,0.63\n600496435,0.69\n600473902,0.64\n600549407,0.79\n600403677,0.64\n600408309,0.74\n600408329,0.67\n600523225,0.73\n600408831,0.79\n600408005,0.75\n600363497,0.82\n600408251,0.76\n600411755,0.73\n600408031,0.72\n600386421,0.77\n600369957,0.79\n600408466,0.77\n600363391,0.79\n600403663,0.79\n600405838,0.79\n600534689,0.79\n600407992,0.79\n600404480,0.79\n600363097,0.83\n600409091,0.86\n600408220,0.81\n600549071,0.85\n600408063,0.86\n600408573,0.87\n600496441,0.89\n600510795,0.89\n600510546,0.92\n600478430,0.96\n600405812,0.33\n600426989,0.62\n600394275,0.63\n600470837,0.55\n600416877,0.54\n600416882,0.55\n600534718,0.57\n600404652,0.62\n600404709,0.62\n600407549,0.62\n600420314,0.66\n600420324,0.68\n600523479,0.62\n600409866,0.64\n600371139,0.71\n600474197,0.64\n600407948,0.66\n600407367,0.65\n600496830,0.66\n600407294,0.68\n600407460,0.69\n600408827,0.75\n600420431,0.68\n600404702,0.76\n600404748,0.72\n600419854,0.71\n600419857,0.71\n600419845,0.71\n600420347,0.76\n600420350,0.73\n600510666,0.73\n600496744,0.73\n600381719,0.73\n600416462,0.74\n600426597,0.74\n600523120,0.74\n600407799,0.75\n600407702,0.77\n600407937,0.77\n600410298,0.77\n600381184,0.73\n600404726,0.75\n600407300,0.79\n600416529,0.79\n600549545,0.79\n600394357,0.8\n600410313,0.8\n600404448,0.81\n600522186,0.8\n600409862,0.81\n600408095,0.82\n600523061,0.82\n600416090,0.83\n600384303,0.86\n600496699,0.86\n600404116,0.88\n600404115,0.92\n600420360,0.95\n600549556,0.96\n600381693,0.96\n600363618,0.73\n600423634,0.81\n600422060,0.93\n600386431,0.95\n600382795,0.0\n600362957,0.29\n600403490,0.61\n600408262,0.82\n600408099,0.82\n600363052,0.23\n600381209,0.51\n600381211,0.4\n600405864,0.4\n600419070,0.54\n600381166,0.6\n600381660,0.6\n600394279,0.7\n600407889,0.7\n600494644,0.72\n600495970,0.75\n600405763,0.76\n600405764,0.76\n600411738,0.8\n600411743,0.8\n600362964,1.0\n600362970,1.0\n600362979,1.0\n600363020,1.0\n600363041,1.0\n600363134,1.0\n600363192,1.0\n600363193,1.0\n600363203,1.0\n600363212,1.0\n600363227,1.0\n600363229,1.0\n600363295,1.0\n600363303,1.0\n600363469,1.0\n600363523,1.0\n600363596,1.0\n600381186,1.0\n600381192,1.0\n600381665,1.0\n600381703,1.0\n600381714,1.0\n600381722,1.0\n600381723,1.0\n600381765,1.0\n600381832,1.0\n600382161,1.0\n600382571,1.0\n600382573,1.0\n600382799,1.0\n600385237,1.0\n600385238,1.0\n600385277,1.0\n600388043,1.0\n600389403,1.0\n600389549,1.0\n600389608,1.0\n600389988,1.0\n600390151,1.0\n600394187,1.0\n600403745,1.0\n600404114,1.0\n600404117,1.0\n600404463,1.0\n600404670,1.0\n600405951,1.0\n600407308,1.0\n600407316,1.0\n600407323,1.0\n600407374,1.0\n600407905,1.0\n600407984,1.0\n600408020,1.0\n600408352,1.0\n600408571,1.0\n600408598,1.0\n600408602,1.0\n600412322,1.0\n600416054,1.0\n600416546,1.0\n600416561,1.0\n600416573,1.0\n600416641,1.0\n600416870,1.0\n600416876,1.0\n600417951,1.0\n600418408,1.0\n600419054,1.0\n600421011,1.0\n600421750,1.0\n600421754,1.0\n600426547,1.0\n600472853,1.0\n600473654,1.0\n600473880,1.0\n600494472,1.0\n600496152,1.0\n600496464,1.0\n600496482,1.0\n600496745,1.0\n600505927,1.0\n600505928,1.0\n600508252,1.0\n600508280,1.0\n600509045,1.0\n600510877,1.0\n600522272,1.0\n600522545,1.0\n600523394,1.0\n600523623,1.0\n600529335,1.0\n600534662,1.0\n600535064,1.0\n600535111,1.0\n600536745,1.0\n600537172,1.0\n600537210,1.0\n600537212,1.0\n600537386,1.0\n600537387,1.0\n600537906,1.0\n600549186,1.0\n600549440,1.0\n600549476,1.0\n600549509,1.0\n600496453,0.89\n600405897,0.96\n600363176,0.96\n600508702,0.41\n600421898,0.36\n600407785,0.58\n600410457,0.71\n600499187,0.71\n600620551,0.51\n600745389,0.51\n600629571,0.56\n600744609,0.73\n600746866,0.79\n600745380,0.79\n600745395,0.79\n600745385,0.82\n600746911,0.88\n600587524,0.0\n600632067,0.0\n600640419,0.0\n600738266,0.0\n600587539,0.24\n600746844,0.62\n600563503,0.42\n600751489,0.53\n600631953,0.64\n600692062,0.56\n600752157,0.58\n600752167,0.74\n600742775,0.65\n600740931,0.61\n600637673,0.69\n600738816,0.75\n600750532,0.74\n600654000,0.79\n600746846,0.81\n600622988,0.81\n600747374,0.81\n600741867,0.84\n600631968,0.85\n600563588,0.87\n600628344,0.87\n600748337,0.92\n600660617,0.0\n600701536,0.0\n600577098,0.0\n600763538,0.0\n600574900,0.0\n600672363,0.25\n600699756,0.46\n600563738,0.33\n600763108,0.47\n600763107,0.53\n600610494,0.58\n600620428,0.47\n600763094,0.5\n600763096,0.5\n600763100,0.5\n600761694,0.59\n600573187,0.62\n600582904,0.56\n600627900,0.56\n600618921,0.67\n600665053,0.59\n600754639,0.61\n600637234,0.62\n600637228,0.64\n600701619,0.64\n600762763,0.64\n600664683,0.64\n600682485,0.66\n600563538,0.67\n600620791,0.67\n600699306,0.69\n600762374,0.64\n600762040,0.73\n600664634,0.72\n600700110,0.72\n600762042,0.73\n600665065,0.82\n600637404,0.73\n600637455,0.73\n600761180,0.73\n600761708,0.74\n600699135,0.82\n600575311,0.77\n600763514,0.79\n600675655,0.8\n600582890,0.79\n600582931,0.8\n600758947,0.84\n600753395,0.84\n600762366,0.89\n600759634,0.88\n600763512,0.89\n600699299,0.89\n600762778,0.89\n600762789,0.89\n600755731,0.9\n600582702,0.91\n600585780,0.94\n600762007,0.38\n600628304,0.34\n600583514,0.38\n600682561,0.66\n600664657,0.49\n600701627,0.49\n600761999,0.49\n600699906,0.5\n600628322,0.5\n600763093,0.5\n600761666,0.53\n600761683,0.56\n600582929,0.56\n600549589,0.57\n600654688,0.57\n600763109,0.59\n600761713,0.65\n600583759,0.66\n600628313,0.66\n600627534,0.67\n600667099,0.67\n600637611,0.68\n600763454,0.68\n600763456,0.68\n600761975,0.71\n600640161,0.71\n600673101,0.71\n600763394,0.75\n600763417,0.71\n600637624,0.73\n600664255,0.72\n600575318,0.74\n600760377,0.74\n600763070,0.76\n600611036,0.77\n600667123,0.77\n600762709,0.77\n600762688,0.77\n600763397,0.77\n600763427,0.77\n600551258,0.77\n600699549,0.77\n600551256,1.0\n600563151,1.0\n600563163,1.0\n600563201,1.0\n600563636,1.0\n600563646,1.0\n600563655,1.0\n600563775,1.0\n600573267,1.0\n600574889,1.0\n600574912,1.0\n600575089,1.0\n600575713,1.0\n600582705,1.0\n600582891,1.0\n600582916,1.0\n600582943,1.0\n600583114,1.0\n600583121,1.0\n600583249,1.0\n600583515,1.0\n600583754,1.0\n600587707,1.0\n600610400,1.0\n600610555,1.0\n600610855,1.0\n600611039,1.0\n600613744,1.0\n600618886,1.0\n600619571,1.0\n600619679,1.0\n600619735,1.0\n600622715,1.0\n600628499,1.0\n600628618,1.0\n600631967,1.0\n600637429,1.0\n600637848,1.0\n600637877,1.0\n600639968,1.0\n600640145,1.0\n600643928,1.0\n600652329,1.0\n600654595,1.0\n600654952,1.0\n600664328,1.0\n600664664,1.0\n600664681,1.0\n600664702,1.0\n600665064,1.0\n600667891,1.0\n600669935,1.0\n600670121,1.0\n600682548,1.0\n600699345,1.0\n600699747,1.0\n600699900,1.0\n600699953,1.0\n600701196,1.0\n600701617,1.0\n600747371,1.0\n600747399,1.0\n600747401,1.0\n600749381,1.0\n600749777,1.0\n600749779,1.0\n600757885,1.0\n600758971,1.0\n600759638,1.0\n600760423,1.0\n600760424,1.0\n600760445,1.0\n600760467,1.0\n600760470,1.0\n600760515,1.0\n600761214,1.0\n600761695,1.0\n600762002,1.0\n600762055,1.0\n600762330,1.0\n600762346,1.0\n600762398,1.0\n600762721,1.0\n600762724,1.0\n600762783,1.0\n600762825,1.0\n600763064,1.0\n600763396,1.0\n600763424,1.0\n600763484,1.0\n600763490,1.0\n600763493,1.0\n600763520,1.0\n600763566,1.0\n600763571,1.0\n600763587,1.0\n600763592,1.0\n600763597,1.0\n600763607,1.0\n600763609,1.0\n600763618,1.0\n600763627,1.0\n600763643,1.0\n600764007,1.0\n600764024,1.0\n600764057,1.0\n600764068,1.0\n600619249,0.77\n600675357,0.77\n600763413,0.77\n600583516,0.8\n600637027,0.79\n600583300,0.8\n600654736,0.79\n600672928,0.8\n600763458,0.69\n600763461,0.79\n600660086,0.82\n600761675,0.82\n600762348,0.83\n600760412,0.88\n600760416,0.88\n600760429,0.88\n600764014,0.91\n600759618,0.92\n600763511,0.86\n600583104,0.93\n600563734,0.97\n600574903,0.97\n600762750,0.73\n600664872,0.5\n600762325,0.66\n600762334,0.73\n600610816,0.73\n600619251,0.76\n600575098,0.78\n600764075,0.78\n600619693,0.8\n600682729,0.8\n600611042,0.2\n600682508,0.77\n600925352,0.36\n600919055,0.51\n600955519,0.71\n601035215,0.73\n600902027,0.79\n600925678,0.8\n600892586,0.79\n600945201,0.0\n600952691,0.0\n601014718,0.0\n601031634,0.0\n600945138,0.3\n600952627,0.47\n600912851,0.69\n600952639,0.6\n601031647,0.61\n601031895,0.76\n600892759,0.88\n600893694,0.21\n600764516,0.0\n600893345,0.27\n600920220,0.39\n601074637,0.6\n600893705,0.47\n600952872,0.48\n600917175,0.53\n600955750,0.57\n600910332,0.71\n600920160,0.59\n601074636,0.61\n600893662,0.62\n601102743,0.69\n601102745,0.7\n601102750,0.69\n600764967,0.68\n600764985,0.68\n600922872,0.66\n600918672,0.64\n601102803,0.83\n601102951,0.64\n600920825,0.69\n600920826,0.67\n601019350,0.69\n600910310,0.69\n600945601,0.7\n600910301,0.7\n601057685,0.71\n600990893,0.72\n600920838,0.73\n600921457,0.75\n600765436,0.73\n600765002,0.73\n601102735,0.74\n601102726,0.74\n600910299,0.74\n601020873,0.76\n600910206,0.75\n600920969,0.75\n600969601,0.75\n600992123,0.75\n600992130,0.75\n601102843,0.75\n600920183,0.77\n601102086,0.77\n601102882,0.78\n601102896,0.78\n601102897,0.78\n600920896,0.75\n600945626,0.75\n600765011,0.78\n601102927,0.78\n600893303,0.79\n600765434,0.8\n600945627,0.82\n600764125,0.87\n600893517,0.87\n600920164,0.91\n600970322,0.93\n600990814,0.93\n600765457,0.94\n600913864,0.94\n600922111,0.94\n600910297,0.28\n601017739,0.31\n600922717,0.45\n600922865,0.45\n600764524,0.51\n600999075,0.65\n601017658,0.53\n601019320,0.52\n600913378,0.54\n600922709,0.54\n600901591,0.56\n600764527,0.62\n600910285,0.75\n601019336,0.65\n600893681,0.64\n600893720,0.64\n600942834,0.73\n600916450,0.66\n600920684,0.65\n600920691,0.66\n600952959,0.67\n600999148,0.67\n600991198,0.73\n600921195,0.71\n600920681,0.71\n600916507,0.73\n600922658,0.73\n600922660,0.73\n600922661,0.73\n600893609,0.71\n600920765,0.74\n600918668,0.75\n600764946,0.75\n600920743,0.77\n600764912,0.78\n600999236,0.77\n600936656,0.77\n600936362,0.79\n600936402,0.79\n600972026,0.79\n600921202,0.8\n600764439,0.8\n600910280,0.82\n600910292,0.81\n600936623,0.83\n600910233,0.84\n600923498,0.84\n600923499,0.84\n600764902,0.86\n600916247,0.78\n600922452,0.87\n600764450,0.87\n601017675,0.92\n601017676,0.92\n601076537,0.73\n600979454,0.44\n600903028,0.73\n600893729,0.93\n601076967,0.93\n600922148,0.6\n600920441,0.62\n600893656,0.69\n600910331,0.83\n601017863,0.78\n600969537,0.79\n600922471,0.96\n600765413,0.66\n600765912,0.66\n600764147,1.0\n600764163,1.0\n600764199,1.0\n600764415,1.0\n600764454,1.0\n600764472,1.0\n600764483,1.0\n600764489,1.0\n600764548,1.0\n600764554,1.0\n600764608,1.0\n600764959,1.0\n600764984,1.0\n600765010,1.0\n600765016,1.0\n600765020,1.0\n600765027,1.0\n600765035,1.0\n600765039,1.0\n600765335,1.0\n600765370,1.0\n600765861,1.0\n600765985,1.0\n600766001,1.0\n600766006,1.0\n600766428,1.0\n600766463,1.0\n600766465,1.0\n600766469,1.0\n600766493,1.0\n600766519,1.0\n600766522,1.0\n600766991,1.0\n600767471,1.0\n600767485,1.0\n600893221,1.0\n600893246,1.0\n600893441,1.0\n600893611,1.0\n600893613,1.0\n600893616,1.0\n600893617,1.0\n600893621,1.0\n600893730,1.0\n600893888,1.0\n600903041,1.0\n600910354,1.0\n600910378,1.0\n600913067,1.0\n600913070,1.0\n600913220,1.0\n600913225,1.0\n600913232,1.0\n600913380,1.0\n600913383,1.0\n600914241,1.0\n600914344,1.0\n600914496,1.0\n600915294,1.0\n600916357,1.0\n600918623,1.0\n600920119,1.0\n600920680,1.0\n600920823,1.0\n600920845,1.0\n600921187,1.0\n600921222,1.0\n600921243,1.0\n600922123,1.0\n600922450,1.0\n600922468,1.0\n600922469,1.0\n600928077,1.0\n600942836,1.0\n600942848,1.0\n600945649,1.0\n600952883,1.0\n600956039,1.0\n600969614,1.0\n600969625,1.0\n600979370,1.0\n600979377,1.0\n600979383,1.0\n600980969,1.0\n600980979,1.0\n600980989,1.0\n600980990,1.0\n600981057,1.0\n600990764,1.0\n600991395,1.0\n601014743,1.0\n601019324,1.0\n601019894,1.0\n601021062,1.0\n601021202,1.0\n601021474,1.0\n601021666,1.0\n601031642,1.0\n601076554,1.0\n601102110,1.0\n601102832,1.

Clearly, we need to work on the structure of this data, since its all being compacted into two columns. We opened the csv file and saved it with a new structure on excel and it seems now more managable.

In [38]:
tomtom = pd.read_csv(r"C:\SAIL-Project\Data\tomtom_updated.csv")

In [39]:
tomtom.head(10)

,time,data
0,2025-08-20T08:36:29.749039+02:00,"id,traffic_level\n210398154,0.69\n209398060,0...."
1,600575534,1
2,600575564,1
3,600575701,1
4,600579214,1
5,600580540,1
6,600582896,1
7,600583302,1
8,600583508,1
9,600583895,1

With this version we can now crete an extra column with the time stamp for each row and drop the row with the timestamp. This will have an associated time and can be used to merge with NWB dataset.

In [47]:
# Detectar las filas que contienen un timestamp ISO
timestamp_pattern = (
    r"^\d{4}-\d{2}-\d{2}T"
    r"\d{2}:\d{2}:\d{2}"
)

tomtom["timestamp"] = tomtom["time"].str.match(
    timestamp_pattern, na=False
)

# Guardar el timestamp solo en las filas donde aparece
tomtom["timestamp"] = tomtom["time"].where(tomtom["timestamp"])

# Propagar el timestamp hacia abajo
tomtom["timestamp"] = tomtom["timestamp"].ffill()

# Eliminar las filas que contienen timestamps
# en lugar de datos de tráfico
tomtom = tomtom[
    ~tomtom["time"].str.match(timestamp_pattern, na=False)
].copy()

# Renombrar las columnas de datos
tomtom = tomtom.rename(columns={
    "time": "id",
    "data": "traffic_level"
})

# Conservar únicamente las columnas necesarias
tomtom = tomtom[["timestamp", "id", "traffic_level"]]

# Limpiar espacios y convertir tipos
tomtom["id"] = pd.to_numeric(tomtom["id"], errors="coerce")
tomtom["traffic_level"] = pd.to_numeric(
    tomtom["traffic_level"], errors="coerce"
)

tomtom = tomtom.dropna(subset=["timestamp", "id", "traffic_level"])

In [48]:
tomtom["id"] = tomtom["id"].astype(int)

In [57]:
tomtom.head()

                          timestamp         id  traffic_level
1  2025-08-20T08:36:29.749039+02:00  600575534            1.0
2  2025-08-20T08:36:29.749039+02:00  600575564            1.0
3  2025-08-20T08:36:29.749039+02:00  600575701            1.0
4  2025-08-20T08:36:29.749039+02:00  600579214            1.0
5  2025-08-20T08:36:29.749039+02:00  600580540            1.0

Now let's check the NWB file

In [58]:
nwb_file.head()

,wvk_id,traffic_le,geometry,id
0,202394085,1.0,"LINESTRING (4.59735 52.45842, 4.59731 52.45845...",202394085
1,202394096,1.0,"LINESTRING (4.5999 52.4607, 4.6004 52.46096, 4...",202394096
2,202394097,1.0,"LINESTRING (4.59909 52.45928, 4.59912 52.45932...",202394097
3,203394034,1.0,"LINESTRING (4.60533 52.46244, 4.60539 52.46238...",203394034
4,203394046,1.0,"LINESTRING (4.60387 52.46187, 4.60396 52.46191...",203394046

In [ ]:
nwb_file["wvk_id"].unique()

<ArrowStringArray>
['202394085', '202394096', '202394097', '203394034', '203394046', '203394065',
 '203394075', '203394089', '203394110', '203394111',
 ...
 '601264536', '601264537', '601264538', '601264539', '601264540', '601264553',
 '601264554', '601264556', '601268741', '601268743']
Length: 10742, dtype: str

The length of this unique array confirms that this dataframe contains one row per id and a linestring associated to each one of the. What we want is to have line strings and traffic flow on the same dataframe so we must join this dataframes.

In [59]:
tomtom["id"] = tomtom["id"].astype(str).str.strip()
nwb_file["id"] = nwb_file["wvk_id"].astype(str).str.strip()

result = tomtom.merge(
    nwb_file,
    on="id",
    how="left"
)

result.head()

,timestamp,id,traffic_level,wvk_id,traffic_le,geometry
0,2025-08-20T08:36:29.749039+02:00,600575534,1.0,600575534.0,1.0,"LINESTRING (4.93581 52.35127, 4.93586 52.35122..."
1,2025-08-20T08:36:29.749039+02:00,600575564,1.0,600575564.0,1.0,"LINESTRING (4.83875 52.3724, 4.83878 52.3724, ..."
2,2025-08-20T08:36:29.749039+02:00,600575701,1.0,600575701.0,1.0,"LINESTRING (4.93953 52.35354, 4.93958 52.35351..."
3,2025-08-20T08:36:29.749039+02:00,600579214,1.0,600579214.0,1.0,"LINESTRING (4.76723 52.46499, 4.76726 52.465, ..."
4,2025-08-20T08:36:29.749039+02:00,600580540,1.0,600580540.0,1.0,"LINESTRING (4.90862 52.36043, 4.90867 52.36044..."